// These workshops are teaching adaptations, not a prescribed study design.
export const ADVANCED_REFERENCES = {
  xr: { label: 'Chirouze, Cleary y Mitchell (2005) · XR', text: 'Chirouze, O., Cleary, D., & Mitchell, G. G. (2005). A software methodology for applied research: eXtreme Researching. Software: Practice and Experience, 35(15), 1441–1454.', url: 'https://doi.org/10.1002/spe.677', note: 'Propone adaptar XP a investigación industrial distribuida. El traslado a una tesis es una adaptación didáctica que debe justificarse.' },
  scientificXp: { label: 'Wood y Kleb (2003) · XP en investigación', text: 'Wood, W. A., & Kleb, W. L. (2003). Exploring XP for scientific research. IEEE Software, 20(3), 30–36.', url: 'https://doi.org/10.1109/MS.2003.1196317', note: 'Experiencia de investigación científica con software; no demuestra por sí misma eficacia en tesis de Psicología.' },
  dojo: { label: 'Hunt y Wang (2013) · Research Dojo', text: 'Hunt, J., & Wang, X. (2013). Research Dojo: Applying agile principles to agile research—Workshop summary from XP2013. ACM SIGSOFT Software Engineering Notes, 38(5), 43–46.', url: 'https://doi.org/10.1145/2507288.2507324', note: 'Informe de taller sobre colaboración investigativa; sus observaciones no equivalen a un ensayo de eficacia.' },
  scrum: { label: 'Senabre Hidalgo (2019) · Scrum en ciencia', text: 'Senabre Hidalgo, E. (2019). Adapting the scrum framework for agile project management in science: Case study of a distributed research initiative. Heliyon, 5(3), e01447.', url: 'https://doi.org/10.1016/j.heliyon.2019.e01447', note: 'Estudio de caso de gestión de investigación. Scrum y XP son enfoques distintos; un sprint pertenece a Scrum y no define el diseño del estudio.' },
  mixed: { label: 'Fetters, Curry y Creswell (2013) · Integración', text: 'Fetters, M. D., Curry, L. A., & Creswell, J. W. (2013). Achieving integration in mixed methods designs—Principles and practices. Health Services Research, 48(6 Pt 2), 2134–2156.', url: 'https://doi.org/10.1111/1475-6773.12117', note: 'La integración debe planificarse en el diseño, los procedimientos y la interpretación. Una matriz es útil cuando permite producir una inferencia conjunta.' }
};

export function methodologyLessons(lesson) { return [
  lesson('cuantitativo', 'Ruta cuantitativa: medir con sentido', 'Diseñar',
    'El enfoque cuantitativo produce y analiza mediciones para describir distribuciones, estimar diferencias o estudiar relaciones. El diseño determina qué inferencias permiten esas mediciones.',
    'Precisar magnitudes y patrones con indicadores vinculados al concepto, haciendo visible su incertidumbre.', 'Cuando la pregunta necesita estimaciones o contrastes y existe una forma defendible de medir.',
    ['Vincula cada variable con una definición conceptual.', 'Describe cómo se observará y con qué instrumento.', 'Justifica diseño, muestreo y tamaño de la muestra.', 'Planifica análisis, supuestos, datos faltantes e incertidumbre.', 'Delimita las inferencias que el diseño permite.'],
    'Ejemplo hipotético: examinar la asociación entre una puntuación de monitoreo y una rúbrica de fundamentación, con medidas justificadas y un diseño explícito.', 'Una correlación positiva demuestra que el simulador causó el aprendizaje.',
    'Una asociación puede tener explicaciones alternativas. La cantidad de datos y una prueba estadística no corrigen por sí solas un diseño insuficiente para atribuir causalidad.',
    'Quieres relacionar confianza percibida y calidad de una justificación. Define dos indicadores diferentes y explica qué conclusión no podrías extraer de una correlación.',
    'Podrías contrastar un autorreporte de confianza con una valoración de la justificación mediante criterios previamente fundamentados. La asociación no demuestra que la confianza cause calidad; tampoco convierte percepción en desempeño.',
    [['question','Pregunta cuantitativa provisional','Qué magnitud, diferencia o relación necesitas conocer.'],['variables','Variables e indicadores','Definición, modo de medición, instrumento y respaldo.'],['design','Diseño, muestra y análisis','Justifica selección, suficiencia, procedimiento y supuestos.'],['limits','Incertidumbre y alcance','Datos faltantes, sesgos y qué no podrás concluir.']],
    ['¿Cada indicador representa el concepto declarado?', '¿Mis inferencias respetan el diseño y la selección de participantes?'], ['quant','manual']),
  lesson('cualitativo', 'Ruta cualitativa: comprender procesos', 'Diseñar',
    'La investigación cualitativa estudia significados, experiencias y procesos en su contexto. Explicita la perspectiva investigadora y cómo se construyen interpretaciones a partir del material.',
    'Comprender cómo las personas interpretan y desarrollan una experiencia, conservando matices y casos que cuestionan la interpretación.', 'Cuando la pregunta exige profundidad contextual y una estrategia interpretativa fundamentada.',
    ['Formula qué experiencia o proceso necesitas comprender.', 'Justifica la tradición o estrategia cualitativa elegida.', 'Define selección de casos, contexto y producción de información.', 'Explica cómo analizarás el material y conservarás una huella de decisiones.', 'Examina reflexividad, discrepancias y límites de transferencia.'],
    'Ejemplo hipotético: analizar cómo estudiantes explican la revisión de una decisión, contrastando entrevistas y registros de la actividad según una estrategia justificada.', 'Es cualitativo porque preguntaré opiniones y copiaré las frases más bonitas.',
    'Las citas ilustran una interpretación; no sustituyen el análisis. El procedimiento debe explicar cómo se pasa del material a categorías o temas, según el enfoque adoptado.',
    'Dos participantes describen de forma opuesta una misma actividad. Explica cómo conservarías esa diferencia y qué contexto buscarías antes de interpretarla.',
    'Mantén ambos relatos y examina situaciones, trayectorias y condiciones de producción. Contrasta interpretaciones con el material y registra tu posición. No descartes un caso por no ajustarse al patrón inicial.',
    [['question','Pregunta cualitativa provisional','Qué experiencia, significado o proceso quieres comprender.'],['strategy','Estrategia y participantes','Fundamento del diseño, selección y suficiencia de la información.'],['analysis','Producción de información y análisis','Cómo registrarás, interpretarás y documentarás decisiones.'],['reflexivity','Reflexividad y rigor','Tu relación con el campo, explicaciones alternativas y límites.']],
    ['¿Mi estrategia analítica es coherente con la pregunta y la perspectiva teórica?', '¿Conservo casos discrepantes y una huella de mis interpretaciones?'], ['qual','manual']),
  lesson('mixto', 'Ruta mixta: integrar para comprender', 'Diseñar',
    'Los métodos mixtos articulan componentes cuantitativos y cualitativos con una razón explícita. La integración relaciona sus resultados para producir una comprensión que los componentes aislados no aportarían.',
    'Relacionar patrones medidos con procesos y explicaciones, incluyendo sus discrepancias.', 'Cuando la pregunta requiere ambos componentes y el equipo puede justificar su integración y viabilidad.',
    ['Explica qué queda sin responder con un solo componente.', 'Elige y fundamenta una secuencia convergente, explicativa o exploratoria.', 'Define cómo se vincularán participantes, datos o fases.', 'Planifica el punto de integración y una matriz por caso o tema.', 'Interpreta coincidencias, complementos y discrepancias.'],
    'En un diseño explicativo secuencial, resultados cuantitativos orientan la selección y las preguntas de una fase cualitativa; después se construye una interpretación conjunta.', 'Usaremos números y entrevistas en capítulos separados; por eso ya está resuelta la integración.',
    'Debes mostrar qué relación tienen los componentes y qué se aprende al integrarlos. Ninguna secuencia queda aprobada por seleccionarla en este simulador.',
    'Caso ficticio: una estudiante puntúa alto en una rúbrica, pero relata inseguridad. Propón una pregunta integradora sin asumir que una de las fuentes está equivocada.',
    '¿Cómo se relacionan la calidad de la justificación observada y la experiencia de incertidumbre en este caso? Habría que contrastar el sentido de la rúbrica, el relato y su contexto antes de interpretar.',
    [['reason','Por qué necesito integrar','Qué no resolvería cada componente por separado.'],['sequence','Diseño y secuencia propuestos','Convergente, explicativo secuencial, exploratorio secuencial u otro justificado.'],['connection','Punto y unidad de integración','Cómo conectarás participantes, fases, datos o temas.'],['joint','Mi matriz de integración prevista','Componente cuantitativo | cualitativo | coincidencia o discrepancia | inferencia conjunta; todavía sin inventar resultados.']],
    ['¿Puedo explicar el aporte conjunto más allá de reunir dos técnicas?', '¿La integración está prevista en los objetivos, el muestreo y el análisis?'], ['mixed','qual','quant'])
]; }

export function collaborationLessons(lesson) { return [
  lesson('xp', 'XP y XR: investigar en colaboración', 'Colaborar',
    'Extreme Programming (XP) surge en desarrollo de software. eXtreme Researching (XR) adapta prácticas de XP al trabajo de investigación aplicada distribuida. Aquí se usan como referentes para organizar la colaboración, con un traslado didáctico explícito a la tesis.',
    'Hacer visible el trabajo, contrastar decisiones tempranamente y construir versiones compartidas con evidencia.', 'Durante la organización y revisión del proyecto. El enfoque y diseño científico se justifican por separado.',
    ['Identifica una necesidad concreta de coordinación.', 'Elige una práctica y explica su adaptación a la investigación.', 'Acuerda un producto pequeño y un criterio verificable.', 'Asigna responsable y revisor diferentes, con rotación entre tareas.', 'Registra qué cambió y revisa si la práctica ayudó al equipo.'],
    'Adaptación didáctica: una persona propone la síntesis de dos antecedentes, otra contrasta las fuentes y ambas integran una versión con límites explícitos.', 'Nuestra metodología científica es XP; por eso el estudio es válido y mixto.',
    'XP y XR orientan prácticas de trabajo. La validez de una afirmación exige evidencia, teoría y método; el consenso del equipo no la garantiza.',
    'El equipo divide capítulos y solo los reúne al final. Propón una práctica inspirada en XP y explica qué problema intentaría resolver.',
    'Podrían revisar e integrar pequeños apartados durante el proceso para detectar cambios de fenómeno o de vocabulario. Es una adaptación propuesta: hay que observar su utilidad y registrar dificultades.',
    [['need','Necesidad del equipo','Qué problema concreto de colaboración observas.'],['adaptation','Práctica y adaptación','Referente, práctica que retomas y cómo cambia al aplicarla a la tesis.'],['agreement','Acuerdo de trabajo propuesto','Producto, evidencia, responsable, revisión y cómo evaluarás su utilidad.']],
    ['¿Distingo organización del equipo y diseño de investigación?', '¿La adaptación tiene fundamento, límites y evidencia de su uso?'], ['xr','scientificXp','dojo','scrum']),
  lesson('iteracion', 'Taller: una iteración con evidencia', 'Colaborar',
    'Una iteración es un ciclo acotado de trabajo y revisión que entrega una versión utilizable. En esta adaptación, el incremento es un producto investigativo pequeño, trazable y revisable. Un sprint es una práctica de Scrum; no se usa como sinónimo obligatorio de XP.',
    'Reducir tareas vagas y detectar dificultades antes de acumular capítulos inconexos.', 'Al planificar el siguiente avance y al revisar lo que dejó el ciclo anterior.',
    ['Elige una incertidumbre prioritaria del proyecto.', 'Define un incremento realizable y criterios de aceptación.', 'Acuerda fecha, responsable, revisor y evidencia.', 'Desarrolla y contrasta la versión en la mesa del equipo.', 'Cierra con lo aprendido, pendientes y el ajuste del próximo ciclo.'],
    'Incremento propuesto: una matriz comparativa de tres antecedentes. Criterio: cada afirmación remite a una sección leída y se explicita un límite. Fecha y roles se acuerdan con el equipo.', 'Esta semana terminaremos toda la tesis; está lista cuando nadie diga nada.',
    'La planificación concreta permite revisar un producto. El silencio no es revisión ni acuerdo; terminar una tarea tampoco prueba calidad científica.',
    'Convierte «avanzar el marco teórico» en un incremento revisable con evidencia, criterio de aceptación y una pregunta para la retrospectiva.',
    'Ejemplo: comparar dos definiciones del concepto y redactar una justificación provisional con fuentes. Criterio: distinguir sus alcances. Retrospectiva: ¿qué facilitó o dificultó verificar los pasajes?',
    [['increment','Incremento de esta iteración','Una pregunta pendiente y un producto pequeño que ayude a resolverla.'],['criteria','Criterios de aceptación','Qué debe poder comprobar el revisor; no solo cantidad de páginas.'],['roles','Personas y fecha acordadas o propuestas','Responsable, revisor distinto, plazo y estado del acuerdo.'],['evidence','Evidencia y estado real','Ubicación de la versión y fuentes, qué se hizo y qué sigue pendiente.'],['retrospective','Retrospectiva y próximo ajuste','Después del ciclo: qué aprendimos, qué mantendremos y qué cambiaremos; antes, registra las preguntas a revisar.']],
    ['¿El incremento aporta a una pregunta u objetivo de la investigación?', '¿Los criterios, la revisión y los pendientes tienen evidencia identificable?'], ['xr','scrum','dojo']),
  lesson('pares', 'Taller: revisar, integrar y aprender', 'Colaborar',
    'La revisión en pares de esta aula es una lectura crítica interna: otra persona contrasta el aporte, pregunta por su fundamento y propone ajustes. La responsabilidad compartida conserva la autoría y el historial de cada intervención.',
    'Mejorar el argumento y aprender a justificar decisiones antes de integrar una versión.', 'Cuando existe una propuesta propia con evidencia que otra persona pueda consultar.',
    ['Lee la propuesta y abre su evidencia.', 'Distingue qué está respaldado, qué falta y qué excede los datos.', 'Formula una pregunta específica y una mejora prioritaria.', 'El responsable justifica qué mantiene o modifica.', 'Registra la nueva versión y solicita su revisión; conserva objeciones.'],
    '«La fuente informa satisfacción. ¿Qué evidencia permitiría sostener tu afirmación sobre aprendizaje? Sugiero delimitar la frase y buscar una medida pertinente».', '«Todo bien» o «esto está mal», sin explicar el fundamento.',
    'Una devolución útil conecta criterio, evidencia y siguiente acción. Revisar internamente no equivale a revisión editorial de una revista ni sustituye la evaluación académica.',
    'Revisa: «Todos mejoran su razonamiento porque a cinco voluntarios les gustó la actividad». Escribe una pregunta, una mejora prioritaria y qué respaldo pedirías.',
    'Pregunta por la medida de razonamiento y por el alcance de cinco voluntarios. Prioriza distinguir satisfacción y desempeño. Solicita instrumento, procedimiento y registro; no inventes resultados que reparen la frase.',
    [['proposal','Propuesta que someto a revisión','Versión y afirmación concreta, con sus fuentes.'],['review','Pregunta y observación del par','Identifica si es una revisión recibida o una pregunta que preparas; no atribuyas intervenciones inexistentes.'],['response','Respuesta razonada e integración','Qué mantienes, qué cambia y por qué; conserva desacuerdos y lo pendiente.'],['trace','Huella de la decisión','Versiones, evidencia y qué debe volver a revisar el equipo.']],
    ['¿La devolución se apoya en un criterio y en evidencia consultable?', '¿Cada persona registra su propia revisión o acuerdo con la versión vigente?'], ['dojo','scientificXp','feedback'])
]; }

export const METHOD_ROUTES = [
  { id:'cuantitativo', label:'Cuantitativa', verb:'Medir y relacionar', question:'¿Qué relación existe entre indicadores de monitoreo y calidad de la justificación?', evidence:'Mediciones justificadas, procedimiento de puntuación y características de la muestra.', analysis:'Describir distribuciones y estimar relaciones con su incertidumbre, según supuestos y diseño.', limit:'Una asociación no establece causalidad. Confianza percibida y desempeño requieren indicadores distintos.' },
  { id:'cualitativo', label:'Cualitativa', verb:'Comprender en contexto', question:'¿Cómo explican los estudiantes que revisan y fundamentan sus decisiones?', evidence:'Relatos, registros de actuación y contexto, con selección y producción de información justificadas.', analysis:'Interpretar el material mediante una estrategia explícita, con reflexividad y casos discrepantes.', limit:'Las citas no sustituyen el análisis. Las explicaciones retrospectivas no revelan por sí solas todo el proceso.' },
  { id:'mixto', label:'Mixta', verb:'Relacionar las evidencias', question:'¿Cómo ayudan las explicaciones de los estudiantes a comprender los patrones observados en su actuación?', evidence:'Componentes cuantitativo y cualitativo vinculados por casos, temas o fases según el diseño.', analysis:'Integrar en una matriz o argumento conjunto, examinando convergencias y discrepancias.', limit:'Aplicar encuesta y entrevista no basta. Debes justificar qué se integra, cuándo y para responder qué.' }
];

export const RESEARCH_READINGS = [
  { ref:'xr', tag:'XP → investigación', contribution:'Un punto de partida para argumentar la adaptación de prácticas colaborativas a la investigación aplicada.', prompt:'¿Qué práctica necesita nuestro equipo y qué cambia al trasladarla desde investigación industrial?' },
  { ref:'scientificXp', tag:'Experiencia científica', contribution:'Una experiencia de exploración de XP en investigación apoyada en software.', prompt:'¿Qué condiciones de ese contexto coinciden con las nuestras y cuáles no?' },
  { ref:'dojo', tag:'Aprender con pares', contribution:'Un taller que explora la colaboración y las diferencias entre investigar y desarrollar software.', prompt:'¿Cómo diseñaríamos una sesión breve que produzca una pregunta mejor fundamentada?' },
  { ref:'scrum', tag:'Gestión del trabajo', contribution:'Un estudio de caso sobre la adaptación de Scrum a una iniciativa de investigación distribuida.', prompt:'¿Qué problema de coordinación queremos resolver y cómo evaluaríamos el ajuste?' }
];
