// Original teaching adaptations. The methodological references are attached
// to each stable lesson id; worked examples are explicitly hypothetical.
const unit=(explanation,distinction,walkthrough)=>({explanation,distinction,walkthrough:walkthrough.map(([action,reason])=>({action,reason}))});
export const DEEP_TEACHING={
tema:unit('Un interés se transforma en investigación cuando deja abierta una pregunta que puede examinarse con evidencia. Separa el asunto que te interesa, la situación que observas y lo que necesitas conocer. Una experiencia personal puede iniciar la indagación, pero su frecuencia y sus causas requieren respaldo. El protoobjetivo permite explorar sin presentar como definitiva una decisión que las lecturas pueden cambiar.','Investigar una experiencia de aprendizaje y evaluar si una plataforma es fácil de usar son propósitos distintos. Compara alternativas y elige qué conocimiento quieres producir. Una formulación investigable admite hallazgos inesperados.',[
['Parto de «me interesa la simulación».','Es un campo amplio; todavía no indica un proceso ni una incógnita.'],
['Preciso «cómo se revisan decisiones durante una práctica».','Paso del dispositivo al proceso que deseo conocer.'],
['Propongo comprender cómo estudiantes explican esa revisión.','Las lecturas deben ayudar a justificar participantes, contexto y relevancia.']]),
delimitacion:unit('La delimitación funciona como un acuerdo sobre el alcance. El fenómeno expresa qué proceso mirarás; los participantes indican en quiénes; el contexto identifica las condiciones que pueden darle sentido. El período se incorpora cuando afecta el acceso o la interpretación. Revisa cada componente preguntando qué cambiaría en el estudio si lo sustituyeras por otro.','La población de interés, las personas accesibles y la muestra finalmente estudiada pueden ser distintas. Nombrar «estudiantes de Chile» no significa que un grupo de una institución represente a todos. Declara esas distancias.',[
['Fenómeno: fundamentación de una decisión.','Especifica el proceso, no solo la actividad donde ocurre.'],
['Participantes: estudiantes con una experiencia formativa definida.','Los criterios deben ser pertinentes y factibles de comprobar.'],
['Contexto: una situación y un período delimitados.','Conserva esas condiciones en pregunta, objetivos, selección y conclusiones.']]),
busqueda:unit('Buscar implica decidir cobertura y pertinencia. La consulta exploratoria ayuda a aprender el vocabulario del campo; una consulta estructurada documenta cómo construyes el corpus. Distingue descriptores controlados, palabras de los autores y traducciones. Prueba si recuperas documentos pertinentes conocidos y revisa por qué una consulta los pierde. La lectura de resultados también puede cambiar tus términos iniciales.','La cantidad de coincidencias no mide calidad. Amplía cuando pierdes evidencia relevante; restringe cuando el ruido impide revisar con criterios. La fecha, los filtros y la colección forman parte de la estrategia. Cada ajuste necesita una razón.',[
['Decido si necesito definir un concepto o conocer hallazgos.','La función del documento orienta la búsqueda de teoría, revisiones o estudios originales.'],
['Pruebo términos y leo títulos, resúmenes y descriptores.','Detecto vocabulario omitido antes de cerrar la consulta.'],
['Registro cadena, fuente, fecha, filtros y selección.','Otra persona debe poder comprender el recorrido y sus límites.']]),
booleanas:unit('Piensa cada término como un conjunto de documentos. OR reúne conjuntos y admite alternativas; AND conserva su intersección. Por eso los sinónimos suelen unirse con OR y los conceptos que deben coexistir se conectan con AND. Los paréntesis hacen visible qué operación quieres realizar primero. Cada base puede interpretar de forma particular campos, frases, acentos y truncamientos.','NOT puede retirar documentos útiles que mencionan ambos asuntos. No lo uses solo para obtener menos resultados. Una cadena se evalúa examinando qué recupera y qué pierde; su apariencia ordenada no garantiza sensibilidad ni precisión.',[
['Creo el bloque (estrés OR stress).','El documento puede usar cualquiera de las dos expresiones.'],
['Agrego AND (estudiantes OR students).','Exijo un segundo concepto conservando sus alternativas lingüísticas.'],
['Pruebo y comparo los documentos pertinentes.','Antes de añadir un contexto específico, reviso si se expresa con otro vocabulario.']]),
pico:unit('PICO y SPIDER descomponen una necesidad de información. PICO se formuló para preguntas clínicas estructuradas; SPIDER ofrece componentes para buscar evidencia cualitativa y mixta. La elección sigue la evidencia que necesitas. Puedes organizar una pregunta con varios componentes y usar solo algunos como bloques si los restantes restringen demasiado la recuperación.','Las herramientas no asignan un enfoque. Tampoco toda pregunta necesita intervención o comparación. Si adaptas un componente, explica el cambio y conserva el significado de la versión original. Usar ambas siglas no convierte un estudio en mixto.',[
['Para comprender experiencias, identifico muestra y fenómeno con SPIDER.','Ordeno la necesidad de información sin anticipar el hallazgo.'],
['Si necesito contrastar una intervención, examino qué aporta PICO.','La comparación y el resultado deben existir en la pregunta; no se inventan para llenar casillas.'],
['Pruebo qué componentes incluir en la consulta.','Algunos pueden orientar selección y lectura sin funcionar como filtros iniciales.']]),
flujo:unit('El flujo muestra el recorrido de selección y la bitácora conserva sus decisiones. Define qué cuentas: una referencia recuperada es un registro; un texto que comunica resultados es un informe; un estudio puede originar varios informes. Antes de sumar, revisa qué corresponde a duplicación y qué aporta información distinta sobre el mismo estudio.','No recuperar un texto completo es diferente de leerlo y excluirlo. Documenta ambas situaciones. PRISMA orienta el reporte de revisiones sistemáticas; utilizar un flujo para ordenar antecedentes no acredita que realizaste una revisión sistemática.',[
['Identifico duplicados contrastando DOI y metadatos.','Una coincidencia parcial requiere revisión antes de eliminar.'],
['Aplico criterios y documento el paso a texto completo.','Selecciono por pertinencia y alcance, no por resultados favorables.'],
['Comparo las cifras con la lista documental y las razones.','Una suma correcta necesita documentos y decisiones que la respalden.']]),
antecedentes:unit('Leer críticamente implica reconstruir qué pregunta respondió un estudio, cómo produjo evidencia y hasta dónde llega su conclusión. Una matriz permite comparar esas relaciones. Anota el pasaje que sustenta tu síntesis y distingue lo informado por los autores de tu interpretación. Si solo leíste el resumen, registra ese alcance y deja pendiente lo que exige el texto completo.','La síntesis organiza coincidencias, diferencias de contexto, métodos y tensiones. Una lista de autores con sus resultados todavía no explica qué sabe el campo ni qué pregunta permanece abierta.',[
['Identifico qué se midió o interpretó y con quiénes.','El nombre general del instrumento no basta para conocer el constructo observado.'],
['Formulo una afirmación proporcional al diseño.','Confianza percibida no demuestra por sí sola transferencia a otra tarea.'],
['Comparo con otra fuente pertinente.','La diferencia puede provenir del contexto, del procedimiento o del concepto.']]),
concepto:unit('Un concepto orienta qué observas y qué consideras evidencia. Construir un lente requiere comparar definiciones, elegir una con razones y explicitar sus límites. Después identifica dimensiones o procesos que permitan reconocerlo en el material. La traducción debe conservar el significado: una medida disponible no sustituye el concepto sin justificación.','Conocimiento metacognitivo, regulación, confianza y rendimiento pueden relacionarse, pero no significan lo mismo. Para estudiar regulación, explica cómo reconocerás planificación, monitoreo o ajuste según tu marco. En lo cualitativo, declara cuánto orientan las categorías previas y cuánto permanece abierto.',[
['Comparo definiciones y las preguntas que permiten formular.','La elección teórica debe cumplir una función en el problema.'],
['Distingo el concepto de otros cercanos.','Evito tratar seguridad percibida como evidencia directa de regulación.'],
['Propongo material para examinar sus dimensiones.','Conecto definición, instrumentos y análisis conservando decisiones pendientes.']]),
embudo:unit('El embudo construye el argumento desde un campo relevante hasta un problema delimitado. Cada párrafo prepara una necesidad que el siguiente desarrolla. No basta comenzar por el mundo, pasar por Chile y terminar en una institución: la escala geográfica solo ayuda cuando resulta pertinente al fenómeno. Busca una secuencia de razones respaldadas que haga comprensible por qué surge tu pregunta.','El índice invertido se realiza después de escribir: resume en una frase la función de cada párrafo. Dos funciones iguales pueden revelar repetición; un concepto sin preparación señala un puente pendiente. Es una herramienta didáctica del manual, no un diseño metodológico.',[
['Explico qué situación merece atención y con qué respaldo.','La relevancia debe conducir al fenómeno y evitar generalidades sin función.'],
['Comparo evidencia mediante un lente definido.','Presento conocimiento, diferencias y límites que afectan la comprensión.'],
['Formulo qué permanece abierto y reviso el índice invertido.','La pregunta surge de esa tensión; cada párrafo debe aportar al recorrido.']]),
negativo:unit('En la organización didáctica del manual, el estado del arte negativo examina los límites de las aproximaciones disponibles para comprender tu fenómeno. No significa reunir malos resultados. Reconoce primero qué aporta cada enfoque y después explica qué dimensión deja parcialmente esclarecida, con respaldo en la comparación del corpus.','Una limitación que reconocen los autores y una pregunta que tú formulas desde otro lente son cosas distintas. Identifica cuál planteas. Evita declarar que todo el campo ignora un proceso si tu búsqueda cubrió algunas bases, idiomas o períodos.',[
['Agrupo antecedentes por lo que preguntan y observan.','La agrupación permite documentar una tendencia.'],
['Examino qué dimensión queda fuera de esos procedimientos.','Medir satisfacción puede dejar abierta la fundamentación, sin invalidar el estudio de satisfacción.'],
['Redacto una síntesis crítica acotada al corpus.','Fundamento el límite reconociendo los aportes de la evidencia disponible.']]),
positivo:unit('El estado del arte positivo, en este uso didáctico, reúne antecedentes que permiten construir tu aproximación: conceptos, procedimientos o hallazgos que dialogan con el lente elegido. «Positivo» no significa resultados favorables a una plataforma ni confirmación de una hipótesis. Es una función argumentativa que conviene explicitar porque la etiqueta no es universal.','Retomar un estudio exige precisar qué transfieres y qué adaptarás. Una estrategia en formación clínica no se vuelve válida automáticamente en otro contexto. Distingue convergencia teórica, similitud metodológica y coincidencia de resultados.',[
['Selecciono por relación con el concepto y la pregunta.','Un hallazgo discrepante puede ser más pertinente que un resultado alentador.'],
['Explico qué retomo: definición, observación o procedimiento.','La fuente cumple una función concreta en el argumento o diseño.'],
['Declaro diferencias de población, contexto y evidencia.','La adaptación conserva límites y decisiones que todavía requieren justificación.']]),
vacio:unit('Un vacío es una insuficiencia de conocimiento argumentada con lo revisado. Puede referirse a una relación, un proceso, una interpretación o sus condiciones. Muestra primero lo que sí se conoce y después qué sigue abierto. El problema añade por qué esa incertidumbre importa y qué alcance viable tendrá tu aporte.','Que falten estudios en una ciudad no basta. Explica por qué sus condiciones podrían cambiar lo que necesitas comprender. «No encontré» describe una búsqueda; «no existe» exige una afirmación mucho más amplia que suele excederla.',[
['Sintetizo una contribución respaldada por varias fuentes.','La pregunta nueva se construye desde el conocimiento disponible.'],
['Identifico una dimensión insuficientemente esclarecida.','Comparo alcances de diseños y resultados, no solo cantidades de documentos.'],
['Explico relevancia y delimito qué parte estudiaré.','El problema debe conducir a una pregunta abordable con los recursos previstos.']]),
pregunta:unit('La pregunta expresa el compromiso central de conocimiento. Examina interrogante, concepto o relación, fenómeno, participantes y contexto pertinente. Cada palabra tiene consecuencias: preguntar por un efecto exige un diseño distinto de preguntar por experiencias o asociaciones. Una frase breve puede necesitar una explicación de alcance para evitar ambigüedad.','Una pregunta investigable no incorpora una respuesta como premisa. «¿Cómo mejora…?» supone mejora. Preguntar por cambios tampoco resuelve su atribución causal: esta depende del diseño y de cómo se examinan explicaciones alternativas.',[
['Vuelvo al vacío y nombro qué quiero conocer.','La pregunta debe responder a la incertidumbre argumentada.'],
['Pruebo formulaciones que admitan respuestas diferentes.','Si solo permiten confirmar mi expectativa, reviso sus supuestos.'],
['Contrasto componentes con acceso, evidencia y análisis.','La viabilidad delimita qué puedo sostener responsablemente.']]),
objetivos:unit('Los objetivos describen el conocimiento que buscas producir. El general corresponde a la pregunta; los específicos descomponen el propósito en contribuciones relacionadas. Lee cada verbo junto a su objeto: «analizar» por sí solo no define profundidad ni procedimiento. Comprueba además los componentes y cantidades exigidos por la pauta.','Aplicar una entrevista, reclutar participantes o buscar artículos son actividades. Pueden contribuir a un objetivo, pero no reemplazan una contribución cognitiva. Cada específico necesita evidencia prevista, análisis y relación explícita con el general.',[
['General: comprender cómo se fundamentan decisiones en una situación delimitada.','Mantengo el fenómeno, participantes y contexto de la pregunta.'],
['Específicos: describir criterios, analizar su revisión y contrastar explicaciones.','Cada uno aporta conocimiento sin introducir otro estudio.'],
['Escribo evidencia y análisis para cada específico.','Detecto promesas inviables o tareas confundidas con objetivos.']]),
diseno:unit('El enfoque expresa una lógica de producción de conocimiento y el diseño organiza cómo responderás la pregunta. Revisa la evidencia necesaria, su producción, secuencia e inferencias posibles. Es una elección argumentada: la técnica preferida, la cantidad de participantes o la herramienta de búsqueda no la determinan por sí solas.','Cuantitativo, cualitativo y mixto no forman una jerarquía de calidad. Evalúa coherencia y rigor dentro de la propuesta. Lo mixto exige justificar integración y disponer de recursos para desarrollar bien los componentes.',[
['Comparo qué permitirían conocer mediciones y relatos contextualizados.','Evalúo la pregunta antes de elegir instrumentos.'],
['Trazo la secuencia de producción y análisis de información.','Hago visibles dependencias, participantes y momentos de decisión.'],
['Examino límites y una alternativa.','Justifico por qué otra opción respondería menos o excedería la viabilidad.']]),
cuantitativo:unit('Medir exige una conexión defendible entre concepto, variable e indicador. Define qué representa la puntuación, cómo se obtiene y bajo qué condiciones se interpreta. La selección de participantes, los datos faltantes y los supuestos analíticos afectan las conclusiones. Planificarlos antes de conocer resultados reduce decisiones oportunistas.','Una prueba estadística no corrige una medición inadecuada. Una diferencia o asociación requiere tamaño, incertidumbre y contexto. La significación estadística, cuando corresponde utilizarla, no informa por sí sola relevancia práctica ni causalidad.',[
['Distingo confianza percibida y calidad de una justificación.','Son variables distintas y requieren indicadores pertinentes.'],
['Planifico cómo describir y relacionar mediciones.','El procedimiento debe corresponder a escalas, selección y pregunta.'],
['Anticipo explicaciones alternativas.','Una asociación observacional no prueba que una variable cause otra.']]),
cualitativo:unit('La comprensión cualitativa requiere una relación explícita entre pregunta, perspectiva, producción de información e interpretación. Justifica la estrategia y explica cómo pasarás del material a los hallazgos. Conserva contexto, decisiones y discrepancias. La reflexividad examina cómo tu posición y relación con el campo participan en ese proceso.','Codificar no es contar palabras ni escoger citas llamativas. Su significado depende del contexto y la pregunta analítica. Las tradiciones cualitativas no exigen procedimientos idénticos: fundamenta criterios de rigor coherentes con tu enfoque.',[
['Produzco relatos sobre momentos concretos de decisión.','Las preguntas buscan experiencias y razones sin inducir la explicación esperada.'],
['Comparo fragmentos y registro interpretaciones provisionales.','La huella analítica permite discutir cómo construí una categoría o tema.'],
['Busco casos que tensionen la interpretación.','La diferencia puede enriquecer un hallazgo; no se elimina para uniformarlo.']]),
mixto:unit('Integrar es relacionar componentes de forma planificada para producir comprensión conjunta. Puedes conectar fases mediante selección de casos, construir un instrumento desde hallazgos cualitativos o reunir resultados en una matriz. Explica el momento, la unidad que vincula información y la pregunta adicional que permite responder.','Poner puntajes al lado de citas no basta. Una matriz conjunta debe producir una inferencia sobre coincidencias, complementos o discrepancias. La secuencia temporal tampoco define sola el diseño: importa la función de cada fase.',[
['Justifico por qué un componente dejaría incompleta la respuesta.','La integración responde a una necesidad de conocimiento.'],
['Relaciono información por caso, tema o fase.','La correspondencia exige un criterio, no solo disponibilidad de materiales.'],
['Examino puntuación alta y explicación poco fundamentada en un caso ficticio.','La discrepancia exige revisar qué está representando cada componente.']]),
muestra:unit('El muestreo conecta la pregunta con personas o casos que pueden aportar evidencia. Define inclusión, exclusión, acceso, invitación y suficiencia según el enfoque. Una cifra máxima impuesta por tiempo o pauta es una restricción de factibilidad; explica también qué permite conocer y qué limita.','La selección intencional busca casos pertinentes; la representatividad estadística depende de otros procedimientos y supuestos. No atribuyas ambas propiedades a una muestra de conveniencia. Documenta quién queda fuera y sus posibles efectos.',[
['Identifico la experiencia o características necesarias.','Los criterios nacen del fenómeno y de la pregunta.'],
['Contrasto acceso real y estrategia deseada.','Distinguir lo ideal de lo factible permite justificar el alcance.'],
['Explico suficiencia y límites.','Un número no garantiza calidad; importa su relación con diseño e información.']]),
instrumentos:unit('Una técnica produce información; un instrumento concreta cómo registrarla. Vincula objetivo, dimensión, evidencia e instrumento en una matriz. Revisa lenguaje, contexto y condiciones de aplicación. Si adaptas una herramienta, documenta qué cambia y qué respaldo necesita esa versión.','El pilotaje examina comprensión, secuencia, duración y dificultades. No equivale por sí solo a validar un instrumento. Una rúbrica también requiere criterios fundamentados y un proceso para examinar su aplicación.',[
['Objetivo: analizar la fundamentación de decisiones.','Necesito razones, criterios y su relación con evidencia.'],
['Propongo un registro de actuación y una pauta de preguntas.','Distingo lo que la persona hace de lo que explica después.'],
['Pruebo instrucciones y discrepancias de interpretación.','El pilotaje orienta ajustes y revela evidencias de calidad todavía pendientes.']]),
etica:unit('La ética acompaña acceso, relación con participantes, producción de información y comunicación. Describe incomodidades posibles, intereses del equipo y cuidados concretos. El consentimiento debe ser comprensible y la participación voluntaria. Explicita qué se guarda, quién accede y cómo se organiza su conservación.','Si creaste el dispositivo estudiado, reconoce ese interés y examina su influencia. Una actividad formativa no autoriza automáticamente usar registros para investigar. Comprueba exigencias y revisiones institucionales antes de recopilar información.',[
['Identifico relaciones que podrían presionar la participación.','La invitación debe permitir negarse sin consecuencias indebidas.'],
['Separo identificadores del material analítico y defino acceso.','Los cuidados concretos permiten evaluar el procedimiento.'],
['Registro autorizaciones y decisiones pendientes.','Presento el estado real y respeto las revisiones que requiere el proyecto.']]),
analisis:unit('El análisis explica cómo transformarás información en respuestas a tus objetivos. Para cada uno, identifica material, unidad analítica, procedimiento, producto y límite. En lo cuantitativo, revisa supuestos y tratamiento de datos; en lo cualitativo, interpretación y reflexividad; en lo mixto, añade el procedimiento de integración.','Nombrar un programa no describe un análisis. Puede organizar o calcular, pero el equipo decide qué examinar y con qué fundamento. Anticipa información incompleta, discrepancias y resultados contrarios a la expectativa.',[
['Vinculo un objetivo con una fuente de información.','Evito reunir material que no responde a ninguna pregunta.'],
['Explico operaciones que producirán una interpretación o estimación.','Hago visible el paso entre evidencia y afirmación.'],
['Planifico qué revisar si las fuentes no coinciden.','La discrepancia se analiza en lugar de ocultarse.']]),
resultados:unit('Los resultados comunican lo encontrado mediante los procedimientos declarados. Organízalos en relación con los objetivos y localiza su respaldo. Tablas, figuras y fragmentos deben cumplir una función. Conserva diferencias y resultados inesperados; explicar su alcance forma parte del trabajo.','Si aún no recoges datos, presenta un plan o ejemplos identificados como ficticios. Los hallazgos de artículos consultados son antecedentes. Una respuesta de práctica en este simulador tampoco es un dato de tu estudio.',[
['Declaro si estoy diseñando, produciendo o analizando información.','El estado real define qué producto puedo presentar.'],
['Asocio cada hallazgo con objetivo y respaldo.','El lector debe distinguir descripción e interpretación.'],
['Examino discrepancias y límites.','Una conclusión prudente considera también lo inesperado.']]),
discusion:unit('Discutir es interpretar hallazgos en relación con pregunta, marco y antecedentes. Explica coincidencias y diferencias considerando diseños, participantes y contextos. Examina alternativas antes de proponer una explicación. Las limitaciones deben precisar qué inferencias restringen y cómo afectan el aporte.','La conclusión responde dentro de lo que permite el estudio. No añade hallazgos ni convierte una posibilidad en hecho. En un proyecto, formula qué relaciones planeas discutir y qué respuestas permanecen abiertas.',[
['Retomo un hallazgo y su aporte a la pregunta.','Conservo el hilo del proyecto.'],
['Comparo con antecedentes y diferencias metodológicas.','La discrepancia no demuestra por sí sola que un estudio esté equivocado.'],
['Propongo una conclusión acotada y una pregunta futura.','Distingo aporte real y expectativas pendientes de examen.']]),
referencias:unit('La cita vincula una afirmación con una fuente; la referencia permite localizarla. Comprueba autores, año, título, publicación y DOI en el original o metadatos fiables. Revisa además que el contenido respalde lo escrito. Un formato correcto no resuelve una atribución incorrecta.','Parafrasear exige fidelidad y atribución. Una cita textual necesita las condiciones de presentación y localización de APA. Si conoces el trabajo mediante otro, busca el original o declara el uso secundario según la norma.',[
['Marco la afirmación precisa que necesita respaldo.','Una cita no sostiene automáticamente todas las ideas del párrafo.'],
['Contrasto texto, autores, fecha y localizador.','Reviso fidelidad conceptual e identificación documental.'],
['Cruzo citas y lista final.','Cada entrada debe corresponder a un uso real; compruebo los datos pendientes.']]),
defensa:unit('Defender es explicar la cadena de decisiones entre problema, pregunta, objetivos, evidencia y análisis. Practica con lenguaje comprensible y respaldo localizable. Una objeción puede revelar una ambigüedad útil: identifica qué parte afecta y qué necesitarías para resolverla.','La seguridad al hablar no sustituye fundamento. Puedes reconocer una decisión provisional o una limitación y explicar cómo abordarla. Distingue razones científicas de restricciones de viabilidad y exigencias de una entrega.',[
['Explico qué falta comprender y por qué importa.','La audiencia necesita el problema antes de los detalles técnicos.'],
['Relaciono el método con la pregunta y una alternativa.','Muestro razones además del nombre del enfoque.'],
['Respondo una objeción con respaldo, límite y próximo ajuste.','La respuesta abre una revisión fundamentada del argumento.']]),
xp:unit('Las adaptaciones ágiles a investigación hacen visibles productos pequeños, conversaciones de revisión y ajustes frecuentes. Define qué práctica retomas y para qué dificultad. Revisar una afirmación con un par, por ejemplo, puede detectar confusiones antes de integrarla al documento compartido.','XP, Scrum y Kanban no son sinónimos ni determinan el enfoque científico. XP aporta prácticas, Scrum un marco de trabajo y Kanban una estrategia de flujo. Las experiencias consultadas se adaptan a la tesis; no garantizan por sí mismas aprendizaje.',[
['Detecto correcciones tardías de formulaciones contradictorias.','La práctica responde a una necesidad observada.'],
['Propongo revisión por pares de una pieza pequeña.','Acuerdo producto, criterio y evidencia además de responsable.'],
['Examinamos qué ayudó y qué cambiar.','Adoptar un nombre ágil no sustituye evaluar la práctica.']]),
iteracion:unit('Una iteración produce algo revisable: una pregunta argumentada, una matriz contrastada o una sección con fuentes. Define incremento y criterios antes de empezar. Ajusta la escala al tiempo y acceso a evidencia. Al cerrar, compara lo prometido con lo realmente producido.','Terminar una tarea no acredita la validez del contenido. El cierre organiza; la revisión científica examina razones y fuentes. Un bloqueo necesita precisar qué falta y una acción posible, evitando acumular trabajo abierto.',[
['Incremento: comparar dos definiciones y justificar una elección.','Es más revisable que «avanzar el marco teórico».'],
['Criterios: pasajes, diferencias y elección argumentada.','Otra persona sabe qué comprobar.'],
['Retrospectiva: qué funcionó y un ajuste siguiente.','Reviso el proceso desde lo ocurrido, no desde juicios generales sobre el equipo.']]),
pares:unit('Revisar entre pares es conversar sobre un producto con criterios explícitos. El revisor identifica una afirmación, señala respaldo o límite y pregunta para ayudar a decidir. Quien escribió responde con razones y registra qué incorpora, mantiene o deja pendiente. Conservar versiones permite reconstruir ese aprendizaje.','Puede haber consenso sobre una afirmación insuficientemente respaldada. Conserva objeciones pertinentes y distingue problemas de forma, coherencia y método. El acuerdo interpersonal no sustituye el examen científico.',[
['El autor comparte una afirmación y su fuente.','La revisión tiene un objeto concreto, no un juicio sobre la persona.'],
['El par pregunta si se observó desempeño o percepción.','Localiza una inferencia que podría exceder la evidencia.'],
['El autor ajusta el alcance y registra su razón.','La integración conserva una decisión contrastada.']])
};
export const GUIDED_CASES={
orientar:{prompt:'Una estudiante escribe: «Quiero demostrar que mi actividad mejora el razonamiento de todos». ¿Qué decisión inicial abre una investigación defendible?',options:['Elegir inmediatamente una prueba estadística.','Precisar qué quiere conocer y admitir resultados diferentes.','Buscar solo antecedentes favorables.'],answer:1,feedback:'Transforma la expectativa en una intención abierta. Delimita el fenómeno y examina antecedentes; la técnica se justifica después según la pregunta y evidencia necesaria.'},
buscar:{prompt:'La primera cadena entrega pocos resultados y el equipo declara que el fenómeno no se ha estudiado. ¿Cuál es el siguiente paso?',options:['Revisar sinónimos, cobertura y filtros, registrando los ajustes.','Escribir que no existe evidencia.','Exigir que cada título repita exactamente la pregunta.'],answer:0,feedback:'La recuperación depende de la estrategia. Examina qué pudo quedar fuera y compara lo recuperado antes de sostener un vacío. Documenta los cambios.'},
argumentar:{prompt:'Un antecedente mide satisfacción; tu pregunta busca fundamentación de decisiones. ¿Cómo lo usarías?',options:['Como prueba de que las decisiones están bien fundamentadas.','Lo descartaría porque no confirma el argumento.','Como evidencia sobre satisfacción, explicando qué deja abierto sobre fundamentación.'],answer:2,feedback:'Reconoce el aporte dentro de su constructo y diseño. La distancia respecto de tu pregunta puede ayudar a argumentar una necesidad, contrastada con el resto del corpus.'},
formular:{prompt:'La pregunta busca comprender una experiencia y el objetivo específico promete «aplicar diez entrevistas». ¿Qué revisarías?',options:['Mantenerlo porque tiene una cantidad.','Formular qué conocimiento aportarán y conservar su aplicación como actividad.','Cambiar la pregunta para conservar el número diez.'],answer:1,feedback:'El objetivo expresa una contribución de conocimiento. La entrevista es una técnica que debe justificarse; su cantidad no convierte la actividad en objetivo cognitivo.'},
disenar:{prompt:'El equipo propone encuesta y entrevista, pero las analizará sin conectarlas. ¿Qué falta para fundamentar un diseño mixto?',options:['Aumentar las preguntas.','Usar PICO y SPIDER simultáneamente.','Justificar qué aporta integrar y cómo vinculará fases, datos o interpretaciones.'],answer:2,feedback:'La integración responde a una necesidad de conocimiento y tiene un procedimiento explícito. Dos técnicas o herramientas de búsqueda no sustituyen esa decisión.'},
revisar:{prompt:'Una tarea dice «revisar antecedentes», no tiene producto ni criterios y se marca terminada. ¿Qué permitiría revisarla?',options:['Definir producto, criterios verificables y revisión de cierre.','Moverla varias veces para mostrar actividad.','Cambiar el color de la tarjeta.'],answer:0,feedback:'Un incremento revisable muestra qué se produjo y con qué respaldo se comprobó. El tablero ayuda a gestionar; la validez exige examinar contenido y razones.'},
comunicar:{prompt:'Los datos contradicen lo esperado. ¿Cómo construirías una discusión defendible?',options:['Omitir los casos que no coinciden.','Examinar discrepancias, alternativas y límites en relación con la pregunta.','Presentar la expectativa inicial como conclusión.'],answer:1,feedback:'Interpreta la evidencia realmente obtenida. Contrastar explicaciones y reconocer límites permite un aporte proporcional al estudio aunque el resultado sea inesperado.'}
};
