import { ADVANCED_REFERENCES, methodologyLessons, collaborationLessons } from './advancedLearningContent.js';
// Stable identifiers keep student work attached to its original learning unit.
export const LEARNING_STEPS = ['Comprender', 'Ver ejemplos', 'Practicar', 'Aplicar a mi investigación', 'Recibir retroalimentación', 'Comprobar coherencia'];
export const REFERENCES = {
  ...ADVANCED_REFERENCES,
  manual: { label: 'Manual de estudio del equipo (2026)', text: 'Llanos Muñoz, L., Toledo Hein, C. D., & Solís Celedón, P. F. (2026). Manual completo de estudio y dominio de tesis [Documento de estudio interno, versión del 29 de septiembre].', note: 'Base didáctica de los módulos de planteamiento. Sus decisiones metodológicas pendientes no se presentan como acuerdos definitivos.' },
  spider: { label: 'Cooke, Smith y Booth (2012)', text: 'Cooke, A., Smith, D., & Booth, A. (2012). Beyond PICO: The SPIDER tool for qualitative evidence synthesis. Qualitative Health Research, 22(10), 1435–1443.', url: 'https://doi.org/10.1177/1049732312452938' },
  pico: { label: 'Richardson et al. (1995)', text: 'Richardson, W. S., Wilson, M. C., Nishikawa, J., & Hayward, R. S. A. (1995). The well-built clinical question: A key to evidence-based decisions. ACP Journal Club, 123(3), A12–A13.', url: 'https://doi.org/10.7326/ACPJC-1995-123-3-A12' },
  search: { label: 'National Library of Medicine: búsqueda', text: 'National Library of Medicine. (s. f.). PubMed user guide.', url: 'https://pubmed.ncbi.nlm.nih.gov/help/' },
  prisma: { label: 'PRISMA 2020', text: 'PRISMA. (s. f.). PRISMA 2020 flow diagram.', url: 'https://www.prisma-statement.org/prisma-2020-flow-diagram', note: 'Guía de reporte para revisiones sistemáticas. Usar un flujo de selección en una revisión de antecedentes no la convierte en revisión sistemática.' },
  qual: { label: 'Levitt et al. (2018)', text: 'Levitt, H. M., Bamberg, M., Creswell, J. W., Frost, D. M., Josselson, R., & Suárez-Orozco, C. (2018). Journal article reporting standards for qualitative primary, qualitative meta-analytic, and mixed methods research in psychology: The APA Publications and Communications Board task force report. American Psychologist, 73(1), 26–46.', url: 'https://doi.org/10.1037/amp0000151' },
  quant: { label: 'Appelbaum et al. (2018)', text: 'Appelbaum, M., Cooper, H., Kline, R. B., Mayo-Wilson, E., Nezu, A. M., & Rao, S. M. (2018). Journal article reporting standards for quantitative research in psychology: The APA Publications and Communications Board task force report. American Psychologist, 73(1), 3–25.', url: 'https://doi.org/10.1037/amp0000191' },
  feedback: { label: 'Hattie y Timperley (2007)', text: 'Hattie, J., & Timperley, H. (2007). The power of feedback. Review of Educational Research, 77(1), 81–112.', url: 'https://doi.org/10.3102/003465430298487' },
  meta: { label: 'Schraw y Moshman (1995)', text: 'Schraw, G., & Moshman, D. (1995). Metacognitive theories. Educational Psychology Review, 7(4), 351–371.', url: 'https://doi.org/10.1007/BF02212307' },
  apa: { label: 'APA Style: referencias', text: 'American Psychological Association. (s. f.). Reference examples. APA Style.', url: 'https://apastyle.apa.org/style-grammar-guidelines/references/examples' }
};

function lesson(id, title, group, definition, purpose, when, steps, example, weak, explanation, practice, model, fields, coherence, refs = ['manual']) {
  return { id, title, group, definition, purpose, when, steps, example, weak, explanation, practice, model,
    fields: fields.map(([key, label, help]) => ({ key, label, help })), coherence, refs };
}

export const LESSONS = [
  lesson('tema', 'Tema e intención de conocimiento', 'Iniciar',
    'El tema sitúa un campo de interés. La intención de conocimiento expresa qué deseas llegar a comprender; el protoobjetivo la convierte en una meta provisional y revisable.',
    'Dar dirección a la exploración inicial y decidir qué lecturas son pertinentes.', 'Al comenzar y cada vez que una lectura cambie el foco.',
    ['Describe una situación que te interese.', 'Separa tu experiencia personal de lo que necesita evidencia.', 'Formula qué quieres conocer, sin anticipar el resultado.', 'Escribe un protoobjetivo y revisa su alcance.'],
    'Me interesa comprender cómo estudiantes revisan sus decisiones durante una práctica simulada.', 'Quiero demostrar que mi simulador es el mejor.',
    'El primer enunciado abre una indagación; el segundo fija una conclusión y mezcla investigación con promoción.',
    'Transforma «las redes sociales hacen mal» en una intención de conocimiento abierta y delimitable.',
    'Una posibilidad: comprender cómo estudiantes universitarios describen la relación entre su uso nocturno de redes y sus hábitos de descanso. Aún exige antecedentes y delimitación.',
    [['theme','Mi tema','Nombra el campo de interés.'],['intention','Qué quiero conocer','Expresa una incógnita, no un resultado esperado.'],['proto','Protoobjetivo','Formula una meta provisional y explica por qué te importa.']],
    ['¿La intención admite hallazgos que contradigan mis expectativas?', '¿La búsqueda bibliográfica puede ayudar a precisar este tema?']),
  lesson('delimitacion', 'Fenómeno, población y contexto', 'Iniciar',
    'Delimitar es precisar qué ocurre, en quiénes y bajo qué condiciones se estudiará. El fenómeno es el proceso o situación de interés; la población es el colectivo y el contexto reúne las condiciones relevantes.',
    'Hacer viable el estudio y evitar que cambie de objeto entre sus apartados.', 'Antes de cerrar la pregunta y al revisar la viabilidad.',
    ['Describe el fenómeno con palabras observables.', 'Precisa las características relevantes de los participantes.', 'Explicita contexto y período cuando aporten al fenómeno.', 'Distingue el entorno de estudio del proceso que quieres conocer.'],
    'Fenómeno: revisión de decisiones. Población: estudiantes adultos de Psicología. Contexto: prácticas universitarias simuladas.', 'Fenómeno: la plataforma. Población: todas las personas.',
    'La herramienta puede ser el contexto; no reemplaza la definición del proceso psicológico. La población debe ser coherente con el alcance.',
    'Delimita un estudio sobre experiencias de primer empleo: fenómeno, población y contexto.',
    'Por ejemplo: experiencias de adaptación de egresados de una carrera durante sus primeros seis meses de trabajo en una región. La accesibilidad de ese grupo debe comprobarse.',
    [['phenomenon','Mi fenómeno','Qué proceso o situación estudiarás.'],['population','Mi población o participantes','Quiénes y con qué características.'],['context','Mi contexto','Dónde, bajo qué condiciones y en qué período, si es pertinente.']],
    ['¿Mantengo los mismos participantes en pregunta y objetivos?', '¿Distingo la herramienta del fenómeno?']),
  lesson('busqueda', 'Buscar evidencia y elegir fuentes', 'Buscar',
    'La búsqueda bibliográfica localiza documentos pertinentes mediante una estrategia explícita. Una base de datos, un buscador y un repositorio tienen coberturas y filtros diferentes.',
    'Conocer el campo, rastrear conceptos y reunir evidencia que puedas contrastar.', 'Desde la exploración inicial y durante los ajustes del proyecto.',
    ['Define qué necesitas: teoría, estudios empíricos, revisiones o contexto.', 'Elige fuentes por su cobertura y acceso.', 'Prueba términos y consulta los descriptores de cada base.', 'Registra fecha, cadena, filtros y número recuperado.', 'Abre el documento, identifica su versión y registra qué leíste.'],
    'Busco teoría para definir regulación y estudios empíricos para conocer cómo se ha observado. Registro ambas búsquedas por separado.', 'Los primeros cinco resultados bastan y sus resúmenes prueban mi hipótesis.',
    'La pertinencia exige lectura y comparación. Un resumen ayuda a seleccionar, pero no respalda afirmaciones sobre secciones que no has leído.',
    'Necesitas conocer cómo se ha investigado una experiencia educativa. Explica qué buscarías primero y qué documento usarías para definir un concepto.',
    'Una revisión puede orientar el campo; estudios originales permiten examinar procedimientos y hallazgos; trabajos teóricos ayudan a definir el concepto. Cada fuente cumple una función distinta.',
    [['purpose','Propósito de mi búsqueda','Qué conocimiento buscas y por qué.'],['sources','Fuentes y tipos de documentos','Justifica bases, repositorios y tipos de documentos.'],['criteria','Criterios de inclusión y exclusión','Pertinencia, población, período, idiomas y razones; no selecciones por resultado favorable.']],
    ['¿Mis fuentes cubren la disciplina y el contexto?', '¿Distingo documento localizado, resumen leído y texto completo leído?'], ['manual','search']),
  lesson('booleanas', 'Descriptores y cadenas booleanas', 'Buscar',
    'Una cadena booleana combina conceptos buscables: OR reúne alternativas de un concepto, AND exige la presencia de conceptos distintos y NOT excluye términos. Comillas y paréntesis organizan frases y grupos según la base.',
    'Hacer explícita y revisable la lógica de búsqueda.', 'Cuando traduces la pregunta a términos de búsqueda y ajustas su amplitud.',
    ['Identifica dos o tres conceptos centrales.', 'Anota sinónimos, traducciones y descriptores pertinentes.', 'Agrupa alternativas con OR y conecta grupos con AND.', 'Prueba la cadena y revisa resultados pertinentes perdidos o ruido.', 'Adapta la sintaxis a cada plataforma; usa NOT solo con justificación.'],
    '(metacognition OR "metacognitive regulation") AND (simulation OR "virtual patient")', 'metacognition AND "metacognitive regulation" AND simulation AND Chile AND 2027',
    'Exigir simultáneamente todos los sinónimos y detalles puede perder documentos pertinentes. Pocos resultados no demuestran un vacío.',
    'Agrupa estrés / stress y estudiantes / students en dos bloques. Explica por qué no usarías AND entre los sinónimos.',
    '(estrés OR stress) AND (estudiantes OR students). OR admite cualquiera de las alternativas; AND conecta los conceptos. Comprueba la sintaxis en la fuente elegida.',
    [['concepts','Conceptos y sinónimos','Un bloque por concepto; justifica traducciones y descriptores.'],['strategy','Cadena probada y plataforma','Pega la cadena que realmente ejecutaste.'],['adjustment','Ajustes realizados','Explica qué cambió al ampliar o restringir.']],
    ['¿La cadena representa mi pregunta sin imponer resultados?', '¿La bitácora conserva la versión exacta ejecutada?'], ['manual','search']),
  lesson('pico', 'PICO y SPIDER', 'Buscar',
    'Son herramientas para estructurar preguntas y búsquedas. PICO: población, intervención, comparación y resultado. SPIDER: muestra, fenómeno de interés, diseño, evaluación y tipo de investigación, orientado a evidencia cualitativa y mixta.',
    'Ordenar componentes relevantes sin confundir la herramienta de búsqueda con el diseño de investigación.', 'Cuando necesitas aclarar la pregunta o seleccionar términos; no es obligatorio usar ambos.',
    ['Define qué evidencia necesitas.', 'Descompón tu pregunta con la herramienta pertinente.', 'Declara los componentes no aplicables y cualquier adaptación.', 'Prueba búsquedas amplias antes de exigir todos los componentes.'],
    'SPIDER ayuda a buscar experiencias y procesos; PICO puede organizar evidencia sobre intervenciones y resultados. Se justifica qué aporta cada uno.', 'Usar PICO y SPIDER convierte automáticamente mi estudio en mixto.',
    'El enfoque mixto requiere una razón y un procedimiento de integración. En PICO canónico C significa comparación; si una guía usa contexto, debe declarar la adaptación.',
    'Quieres comprender cómo estudiantes viven una entrevista simulada. ¿Qué aporta SPIDER y qué seguiría pendiente?',
    'Ayuda a precisar muestra y fenómeno, y a buscar evidencia cualitativa. No decide por sí mismo el diseño, los instrumentos ni el análisis.',
    [['tool','Herramienta y justificación','PICO, SPIDER, ambas u otra estrategia justificada.'],['components','Mis componentes','Declara comparación o su ausencia; separa el contexto.'],['limits','Límites y adaptación','Qué organiza esta herramienta y qué decisiones no resuelve.']],
    ['¿La herramienta responde al tipo de evidencia buscado?', '¿Justifiqué el enfoque sin deducirlo de una sigla?'], ['pico','spider','manual']),
  lesson('flujo', 'Bitácora y flujo de selección', 'Buscar',
    'La bitácora conserva cada búsqueda; el flujo documenta cuántos registros pasan por cada etapa y por qué se excluyen. Un registro bibliográfico, un informe y un estudio no siempre son equivalentes.',
    'Permitir reconstruir la selección y detectar pérdidas, duplicados o decisiones sin justificación.', 'Desde la primera búsqueda, antes de redactar la síntesis.',
    ['Registra cada búsqueda y exporta los resultados.', 'Identifica duplicados por DOI o metadatos contrastados.', 'Aplica criterios a título y resumen.', 'Recupera y evalúa textos completos; registra razones de exclusión.', 'Distingue informes incluidos y estudios únicos cuando corresponda.'],
    'Ejercicio ficticio: 80 registros recuperados, 10 duplicados, 70 examinados; 50 excluidos, 20 textos buscados, 2 no recuperados, 18 evaluados y 6 excluidos: 12 informes incluidos.', 'Encontré aproximadamente 100 y elegí los que me gustaron.',
    'Los números deben proceder de registros reales y cuadrar. El ejemplo no debe usarse como conteo de tu investigación.',
    'En el ejemplo, ¿por qué 20 textos buscados no equivale a 20 textos evaluados?',
    'Dos no se recuperaron. No se pueden evaluar como textos completos ni confundir esa situación con una exclusión por contenido.',
    [['selection','Procedimiento de selección','Quién seleccionó, cómo resolvieron diferencias y cómo eliminaron duplicados.'],['exclusions','Razones de exclusión','Registra motivo y documento; conserva el respaldo.'],['scope','Alcance de la revisión','Declara si es revisión de antecedentes, sistemática u otro tipo y por qué.']],
    ['¿Los conteos se sostienen en una bitácora y un registro documental?', '¿Evito presentar un flujo simplificado como cumplimiento integral de PRISMA?'], ['manual','prisma']),
  lesson('antecedentes', 'Antecedentes y lectura crítica', 'Argumentar',
    'Un antecedente es una fuente previa que aporta evidencia, conceptos o contexto a una afirmación. Su valor depende de su pertinencia y de lo que su diseño permite sostener.',
    'Construir un argumento basado en comparación, no en una sucesión de resúmenes.', 'Al seleccionar, leer e integrar las fuentes.',
    ['Registra referencia y estado de lectura.', 'Extrae pregunta, participantes, método y hallazgos.', 'Identifica qué afirmación respalda y qué no permite concluir.', 'Compara con otras fuentes y escribe una síntesis.'],
    'Un estudio informa confianza percibida. Sirve para hablar de esa percepción; no demuestra por sí solo calidad del razonamiento.', 'Los participantes están satisfechos, por tanto aprendieron a razonar.',
    'Satisfacción, aprendizaje, desempeño y regulación no son constructos intercambiables.',
    'Una encuesta informa que estudiantes se sienten preparados. Escribe una afirmación respaldada y otra que exceda esos datos.',
    'Respaldada: reportan preparación percibida. Excesiva: su actuación profesional es competente. Faltaría evidencia de actuación y criterios adecuados.',
    [['reference','Fuente y lectura real','Referencia, enlace, sección y qué leíste.'],['finding','Hallazgo y alcance','Qué sostiene y qué no permite afirmar.'],['comparison','Comparación con otras fuentes','Identifica coincidencias, diferencias y su función argumental.']],
    ['¿Cada afirmación remite a una fuente que la sostiene?', '¿Separé resultado observado e interpretación propia?']),
  lesson('concepto', 'Conceptualización y lente teórico', 'Argumentar',
    'Conceptualizar es precisar el significado y los límites de un concepto. El concepto de análisis orienta qué observarás del fenómeno; un indicador expresa cómo reconocerás una dimensión.',
    'Evitar usar palabras como aprendizaje, autorregulación y metacognición como si significaran lo mismo.', 'Antes de interpretar antecedentes y diseñar cómo observar el fenómeno.',
    ['Compara definiciones en fuentes teóricas.', 'Justifica la definición que adoptas.', 'Diferencia conceptos cercanos.', 'Propón dimensiones y reserva la selección de instrumentos para el método.'],
    'La regulación metacognitiva permite atender a planificación, monitoreo y ajuste del razonamiento.', 'Metacognición es usar una plataforma y obtener buena nota.',
    'Una herramienta o una calificación no define el constructo. La relación entre concepto y evidencia debe argumentarse.',
    'Distingue observar que alguien cambia una respuesta y afirmar que monitoreó su comprensión.',
    'El cambio es observable; su motivo necesita evidencia adicional. Puede responder a monitoreo, azar o imitación. No atribuyas un proceso solo por el resultado.',
    [['lens','Concepto y definición adoptada','Autor, definición parafraseada y ubicación.'],['boundaries','Conceptos próximos y diferencias','Qué incluye y excluye tu lente.'],['dimensions','Dimensiones que observaría','Conecta dimensiones con evidencia posible, sin confundirlas con instrumentos.']],
    ['¿Mi lente permite leer el fenómeno que delimitamos?', '¿Mis indicadores futuros representarán el concepto?'], ['manual','meta']),
  lesson('embudo', 'Embudo argumental e índice invertido', 'Argumentar',
    'El embudo enlaza razones que conducen desde la relevancia del campo al vacío y al problema. El índice invertido parte del objetivo provisional para identificar qué apoyos debe construir el texto.',
    'Hacer comprensible por qué la pregunta merece ser investigada.', 'Al planificar y revisar la problematización; puede reconstruirse tras nuevas lecturas.',
    ['Formula la promesa de conocimiento provisional.', 'Identifica qué necesita saber el lector para entenderla.', 'Ordena contexto, evidencia, tensión y lente.', 'Contrasta antecedentes y delimita el vacío.', 'Conecta problema, pregunta y objetivo; pregunta «¿qué aporta este párrafo?».'],
    'La formación exige decisiones justificadas → la literatura observa distintos resultados → esos resultados no revelan todo el proceso → se precisa qué articulación necesitamos comprender.', 'La tecnología es importante. La Psicología existe hace mucho. Por eso estudiaremos metacognición.',
    'Cada tramo debe preparar el siguiente con evidencia pertinente. Ir de un asunto amplio a uno estrecho no basta si faltan conexiones.',
    'Ordena y conecta: una necesidad formativa; antecedentes con límites; una incógnita precisa. Escribe una transición entre cada tramo.',
    'Primero explica la necesidad, después contrasta qué aportan y limitan los estudios, y finalmente formula qué sigue abierto. Las transiciones deben justificar el paso, no solo anunciarlo.',
    [['context','Contexto y relevancia','Qué hace pertinente estudiar el fenómeno; cita evidencia.'],['evidence','Evidencia y tensión','Qué se sabe y por qué resulta insuficiente para esta pregunta.'],['bridge','Lente, contraste y vacío','Explica cómo los antecedentes conducen a la incógnita.'],['argument','Mi embudo integrado','Redacta la secuencia con fuentes y transiciones.']],
    ['¿Cada tramo aporta una razón para el siguiente?', '¿La pregunta y el objetivo se desprenden del argumento?']),
  lesson('negativo', 'Estado del arte negativo', 'Argumentar',
    'En la clasificación didáctica del manual, reconstruye cómo los enfoques dominantes han estudiado el fenómeno y qué dimensiones dejan menos esclarecidas. «Negativo» no califica la calidad ni el signo de los resultados.',
    'Reconocer límites del conocimiento sin descalificar investigaciones.', 'Después de comparar un conjunto de antecedentes pertinentes.',
    ['Compara preguntas y marcos de los estudios.', 'Revisa diseños, medidas y contextos.', 'Identifica patrones y sus límites.', 'Explica qué dimensión sigue abierta desde tu lente.'],
    'Varios trabajos describen percepción y desempeño; necesitamos examinar si también observan la revisión del razonamiento.', 'Estos estudios son negativos porque no encontraron mejoras.',
    'La categoría refiere a su función en el argumento. No debes seleccionar solo resultados que favorezcan tu proyecto.',
    'Tres estudios miden satisfacción. ¿Cómo formularías una limitación sin concluir que son malos?',
    'Responden preguntas sobre satisfacción. Por sí solos no permiten conocer el proceso de fundamentación de decisiones; esa afirmación requiere comprobar sus medidas.',
    [['patterns','Enfoques y patrones del corpus','Compara varias fuentes identificadas.'],['limits','Dimensiones insuficientemente esclarecidas','Señala límites específicos con respaldo.'],['synthesis','Síntesis crítica','Qué permite y qué no permite saber ese conjunto.']],
    ['¿Describo límites comprobados y no carencias supuestas?', '¿La síntesis conduce al vacío que planteo?']),
  lesson('positivo', 'Estado del arte positivo', 'Argumentar',
    'En la clasificación didáctica del manual, reúne antecedentes que han recorrido una vía analítica próxima y muestran que el concepto puede ayudar a estudiar el fenómeno. «Positivo» no significa resultado favorable.',
    'Fundamentar la viabilidad intelectual de la propuesta y reconocer lo ya realizado.', 'Al justificar el lente y precisar el aporte frente a estudios cercanos.',
    ['Busca convergencias entre concepto y fenómeno.', 'Compara población, contexto y procedimientos.', 'Explica qué vía abren esos estudios.', 'Delimita qué puedes retomar y qué no puedes extrapolar.'],
    'Un trabajo vincula monitoreo y argumentación en simulación. Orienta cómo observar su relación, aunque su disciplina y población sean distintas.', 'Solo citaré estudios que concluyan que la tecnología funciona.',
    'La proximidad conceptual es la clave; un hallazgo nulo también puede ser pertinente. Reconoce diferencias y evita afirmar originalidad absoluta.',
    'Un estudio parecido se hizo en otra disciplina. Explica su aporte y el límite de trasladarlo a tu proyecto.',
    'Puede mostrar una estrategia analítica viable. No garantiza iguales resultados en otra población ni reemplaza la justificación contextual.',
    [['convergence','Antecedentes convergentes','Qué relación entre concepto y fenómeno han estudiado.'],['contribution','Qué retomo y por qué','Decisión teórica o analítica que ayuda a fundamentar.'],['difference','Diferencias y límites','Qué queda por justificar para mi población y contexto.']],
    ['¿Reconozco estudios que se acercan a mi propuesta?', '¿Diferencio viabilidad intelectual y resultados favorables?']),
  lesson('vacio', 'Vacío y problema de investigación', 'Argumentar',
    'El vacío expresa una insuficiencia argumentada del conocimiento en el corpus revisado. El problema transforma esa insuficiencia en una necesidad de conocimiento con relevancia disciplinar.',
    'Precisar qué falta comprender y por qué vale la pena investigarlo.', 'Tras contrastar antecedentes y revisar el alcance de la búsqueda.',
    ['Sintetiza lo que se sabe.', 'Identifica la insuficiencia conceptual, metodológica o contextual.', 'Respalda esa lectura con comparaciones concretas.', 'Formula la necesidad de conocimiento y su relevancia.'],
    'En el corpus revisado permanece insuficientemente esclarecida la articulación entre revisión del razonamiento y justificación durante esta experiencia.', 'No encontré resultados con mi cadena, por tanto nadie ha investigado esto.',
    'Una búsqueda puede ser demasiado restrictiva. La ausencia de coincidencias no demuestra una ausencia universal de conocimiento.',
    'Reformula «no existe ninguna investigación sobre mi tema» sin atribuirte una revisión exhaustiva.',
    'En las fuentes y búsquedas descritas se identificó evidencia sobre X, pero quedó poco esclarecido Y. Debes nombrar estudios y explicar sus límites.',
    [['known','Qué se sabe','Síntesis sustentada.'],['gap','Mi vacío provisional','Insuficiencia concreta y límites del corpus.'],['problem','Mi problema y relevancia','Qué necesitamos comprender, en quiénes y por qué importa.']],
    ['¿Mi vacío nace de una comparación y no de un conteo?', '¿El problema mantiene fenómeno, población y contexto?']),
  lesson('pregunta', 'Pregunta de investigación', 'Formular',
    'La pregunta convierte el problema en una interrogación investigable. Precisa qué se desea conocer y no contiene una conclusión que el estudio deba confirmar.',
    'Orientar objetivos y decisiones metodológicas.', 'Cuando el problema tiene respaldo suficiente para una formulación provisional.',
    ['Recupera la incógnita del problema.', 'Explicita fenómeno, participantes y contexto pertinentes.', 'Elige una formulación acorde al alcance.', 'Comprueba que puede responderse con evidencia viable.'],
    '¿Cómo revisan y fundamentan sus decisiones los estudiantes durante una situación simulada?', '¿Por qué nuestra plataforma mejora siempre la metacognición?',
    'La segunda pregunta presupone un efecto. Una pregunta relacional no basta para afirmar causalidad ni define por sí sola un enfoque mixto.',
    'Quita la conclusión anticipada de «¿Por qué todos aprenden mejor con simulación?».',
    '¿Qué cambios, dificultades o continuidades se observan en el proceso estudiado durante la simulación? Define después participantes, condiciones y evidencia necesaria.',
    [['question','Mi pregunta','Una incógnita precisa y comprensible.'],['alignment','Relación con el problema','Explica qué parte del problema responde.'],['feasibility','Alcance y viabilidad','Qué evidencia permitiría responder y qué queda fuera.']],
    ['¿La pregunta mantiene la delimitación?', '¿Admite ausencia de relación, diferencias y resultados inesperados?']),
  lesson('objetivos', 'Objetivo general y específicos', 'Formular',
    'Los objetivos expresan conocimiento que se busca producir. El general recoge la pregunta; los específicos descomponen esa promesa en metas cognitivas coherentes.',
    'Definir qué debe poder responder el estudio.', 'Después de una pregunta provisional y antes de elegir procedimientos.',
    ['Selecciona un verbo cognitivo acorde al alcance.', 'Integra concepto, fenómeno, población y contexto pertinentes.', 'Descompón la meta general en objetivos específicos.', 'Separa metas de conocimiento y tareas metodológicas.'],
    'General: analizar la articulación entre regulación y fundamentación. Específicos: describir manifestaciones, identificar formas de fundamentación y examinar su relación.', 'Objetivos: aplicar encuestas, descargar artículos y hacer un gráfico.',
    'Las tareas son medios. Los objetivos deben indicar qué conoceremos gracias a esos medios.',
    'Transforma «realizar entrevistas» en un objetivo cognitivo y explica qué información falta para completarlo.',
    'Comprender las experiencias de adaptación de los participantes. Falta delimitar quiénes y en qué contexto; entrevistar sería un procedimiento posible.',
    [['general','Mi objetivo general','Verbo cognitivo, concepto o lente, fenómeno, población y contexto.'],['specifics','Mis objetivos específicos','Uno por línea. Formula al menos tres cuando lo solicite la pauta.'],['coverage','Cómo responden a la pregunta','Explica qué aporta cada objetivo y evita abrir otra investigación.']],
    ['¿Cada específico desarrolla el general?', '¿El método futuro responderá a cada objetivo?']),
  lesson('diseno', 'Enfoque y diseño', 'Diseñar',
    'El enfoque orienta el tipo de evidencia y el diseño organiza cómo producirla. En métodos mixtos debe explicarse para qué y cómo se integrarán los componentes.',
    'Justificar una estrategia que permita responder la pregunta.', 'Al pasar del planteamiento al plan metodológico, con revisión académica.',
    ['Explica qué evidencia exige la pregunta.', 'Compara alternativas de diseño.', 'Justifica secuencia, condiciones y alcance.', 'Si es mixto, precisa el punto de integración y el aporte conjunto.'],
    'Comparar registros de actuación con explicaciones de participantes podría aclarar discrepancias entre lo realizado y lo declarado; el diseño concreto debe justificarse.', 'El estudio es mixto porque tiene una encuesta y una entrevista.',
    'La coexistencia de técnicas no explica su integración ni asegura que respondan la misma pregunta.',
    'Un estudiante puntúa alto pero describe dificultades. ¿Qué puede aportar integrar ambas evidencias?',
    'Permite examinar la discrepancia y su contexto, sin asumir que una evidencia anula la otra. Define cuándo y con qué unidad de análisis las compararías.',
    [['approach','Enfoque y razón','Qué necesitas conocer y qué evidencia lo hace posible.'],['design','Diseño y secuencia','Decisiones propuestas y alternativas consideradas.'],['integration','Integración o justificación de no aplicabilidad','Cómo se relacionan componentes si el estudio es mixto.']],
    ['¿El diseño permite responder mis objetivos?', '¿Diferencio propuesta metodológica y decisión ya aprobada?'], ['manual','qual','quant','mixed']),
  ...methodologyLessons(lesson),
  lesson('muestra', 'Participantes y muestreo', 'Diseñar',
    'El muestreo establece cómo se seleccionarán participantes o casos de una población delimitada. Su justificación depende de la pregunta, el enfoque y la viabilidad.',
    'Explicitar a quién representa o a qué contextos puede transferirse el conocimiento producido.', 'Al planificar acceso, reclutamiento y alcance.',
    ['Distingue población y participantes accesibles.', 'Justifica estrategia y criterios de selección.', 'Fundamenta el tamaño o criterio de suficiencia.', 'Reconoce sesgos de acceso y límites de inferencia.'],
    'Seleccionar casos con experiencia pertinente puede servir para comprender un proceso; no garantiza representatividad estadística.', 'Cualquier grupo de 30 personas representa a todos los estudiantes.',
    'Ningún tamaño fijo reemplaza la justificación del muestreo. El número y la estrategia deben ser coherentes con el análisis.',
    'Si solo puedes reclutar voluntarios de una institución, ¿qué límite deberías declarar?',
    'La selección y el contexto pueden condicionar lo observado. No generalices automáticamente a todas las instituciones o estudiantes.',
    [['selection','Estrategia de selección','Cómo y por qué elegirás participantes.'],['criteria','Criterios y suficiencia','Inclusión, exclusión y fundamento del tamaño o suficiencia.'],['limits','Acceso y límites','Viabilidad, sesgos y alcance de inferencias.']],
    ['¿Los participantes cumplen la población definida?', '¿El alcance de mis conclusiones respeta la selección?'], ['quant','qual']),
  lesson('instrumentos', 'Dimensiones, técnicas e instrumentos', 'Diseñar',
    'La técnica es el procedimiento de producción de información; el instrumento concreta su aplicación. Una dimensión conceptual necesita evidencia pertinente para poder analizarse.',
    'Conectar constructos, objetivos y datos.', 'Después de definir conceptos y antes de recoger información.',
    ['Asocia cada objetivo a una dimensión.', 'Explica qué evidencia necesitas.', 'Justifica técnica e instrumento.', 'Revisa respaldo, adecuación y pilotaje; declara lo pendiente.'],
    'Para examinar fundamentos de una decisión, solicitar razones y contrastarlas con una rúbrica podría aportar evidencia; debe justificarse la rúbrica.', 'Una escala de satisfacción mide directamente razonamiento clínico.',
    'Debe argumentarse la relación entre constructo e indicador. Un instrumento conocido no es adecuado para cualquier propósito.',
    'Propón una evidencia para estudiar revisión de decisiones y una limitación de esa evidencia.',
    'Comparar versiones con razones declaradas permite observar cambios; las explicaciones retrospectivas pueden no reconstruir fielmente todo el proceso.',
    [['mapping','Objetivo, dimensión y evidencia','Una relación explícita por objetivo.'],['tools','Técnicas e instrumentos','Origen, pertinencia y uso previsto.'],['quality','Calidad y pilotaje','Qué debes comprobar antes de aplicar.']],
    ['¿Observo lo que definí conceptualmente?', '¿Diferencio autorreporte, proceso y desempeño?'], ['manual','quant','qual']),
  lesson('etica', 'Ética y posición del equipo', 'Diseñar',
    'La reflexión ética examina las condiciones de participación, el cuidado de las personas y la responsabilidad del equipo. La posición investigadora explicita vínculos e intereses que pueden influir en el estudio.',
    'Diseñar una participación informada y un uso responsable de la información.', 'Desde el diseño y durante todo el proceso; antes de reclutar se requieren las revisiones institucionales aplicables.',
    ['Identifica relaciones de poder, riesgos e intereses.', 'Explica participación voluntaria y retiro.', 'Define información necesaria, acceso y resguardo.', 'Registra revisiones, permisos y decisiones pendientes.'],
    'Si el equipo desarrolló el entorno, explicita ese vínculo y cómo evitará orientar la interpretación a validar el producto.', 'Como es educativo no necesitamos discutir consentimiento ni resguardo.',
    'La finalidad educativa no resuelve las decisiones éticas. Esta actividad prepara la revisión institucional y no otorga aprobación.',
    '¿Qué conflicto aparece si quien evalúa una asignatura invita a participar en su investigación?',
    'Puede percibirse presión o temor a consecuencias académicas. Debe justificarse cómo proteger la voluntariedad y separar evaluación y participación.',
    [['risks','Riesgos, relaciones e intereses','Incluye el vínculo del equipo con el entorno.'],['care','Participación y resguardo','Información, voluntariedad, retiro y manejo de datos.'],['pending','Revisiones y autorizaciones','Qué está aprobado, por quién y qué sigue pendiente.']],
    ['¿El procedimiento protege la participación voluntaria?', '¿Declaré los vínculos relevantes del equipo?'], ['manual','qual']),
  lesson('analisis', 'Plan de análisis e integración', 'Diseñar',
    'El plan de análisis explica cómo se transformarán registros en evidencia para responder objetivos. La integración mixta relaciona resultados de componentes con una razón explícita.',
    'Anticipar una ruta analítica justificable.', 'Antes de recoger datos, admitiendo ajustes documentados.',
    ['Vincula objetivo, dato y procedimiento.', 'Justifica criterios analíticos y supuestos.', 'Define tratamiento de discrepancias e información faltante.', 'Si corresponde, diseña una matriz de integración por caso o tema.'],
    'Una matriz por caso compara evidencia de actuación y explicaciones, conservando coincidencias y discrepancias.', 'Juntaremos todos los datos y veremos qué sale.',
    'El análisis debe responder una pregunta reconocible; los ajustes posteriores requieren justificación.',
    'Si una fuente contradice a otra, ¿por qué no conviene eliminarla para que el resultado sea uniforme?',
    'La discrepancia puede aportar conocimiento. Revisa calidad, contexto y alcance de ambas antes de interpretar.',
    [['plan','Objetivos y procedimientos de análisis','Indica datos, unidad y procedimiento por objetivo.'],['integration','Comparación e integración','Cómo tratarás convergencias y discrepancias.'],['limits','Supuestos y decisiones pendientes','Qué requiere justificación o asesoría metodológica.']],
    ['¿Cada objetivo tiene una estrategia de análisis?', '¿Evito presentar asociaciones como causas?'], ['manual','qual','quant','mixed']),
  lesson('resultados', 'Resultados y evidencia', 'Comunicar',
    'Los resultados presentan lo encontrado mediante el análisis realizado. Una expectativa o una ilustración no es un hallazgo.',
    'Responder objetivos con evidencia trazable.', 'Después de recoger y analizar datos; antes solo se planifica la presentación.',
    ['Ordena hallazgos por objetivos.', 'Identifica la evidencia que respalda cada afirmación.', 'Incluye resultados discrepantes o nulos.', 'Separa descripción del hallazgo e interpretación.'],
    'Antes de ejecutar el estudio: «Se prevé comparar los casos; aún no hay resultados».', 'La simulación mejorará la regulación; ese es nuestro resultado.',
    'La conclusión anticipada confunde expectativa con evidencia.',
    'Un proyecto todavía no recoge datos. ¿Qué puede escribir en este apartado?',
    'Puede describir un plan de tablas o categorías y dejar explícito que no hay hallazgos. No debe rellenarlo con resultados ficticios.',
    [['status','Estado real del estudio','Planificado, recogida en curso o analizado.'],['findings','Hallazgos o plan de presentación','Identifica explícitamente cuál de los dos registras.'],['evidence','Respaldo y límites','Vincula datos, análisis y afirmaciones; no incluyas datos personales aquí.']],
    ['¿Mis afirmaciones proceden de datos analizados?', '¿Responden a los objetivos planteados?'], ['manual','quant','qual']),
  lesson('discusion', 'Discusión, límites y conclusiones', 'Comunicar',
    'La discusión interpreta hallazgos en diálogo con teoría y antecedentes. Las conclusiones responden la pregunta dentro del alcance del estudio.',
    'Explicar el aporte y sus límites.', 'Cuando existen resultados y se han contrastado con la literatura.',
    ['Responde qué significan los hallazgos.', 'Compara convergencias y diferencias con antecedentes.', 'Considera explicaciones alternativas y limitaciones.', 'Formula conclusiones proporcionadas y preguntas futuras.'],
    'Lo observado en un caso simulado permite discutir ese contexto; no acredita transferencia a pacientes reales.', 'Un resultado favorable prueba que sirve para todas las personas y situaciones.',
    'La generalización y la transferencia requieren justificación; no se derivan de una valoración favorable.',
    'Escribe una limitación para un estudio en una sola institución y explica su consecuencia.',
    'Las condiciones de esa institución pueden influir en los hallazgos. Deben describirse y limitar la extensión de las conclusiones.',
    [['interpretation','Interpretación o plan de discusión','Relaciona hallazgos con teoría; declara si todavía es un plan.'],['limitations','Limitaciones y alternativas','Qué explicación rival o condición restringe la interpretación.'],['conclusions','Conclusiones o preguntas pendientes','Responde dentro del alcance; no anticipes resultados.']],
    ['¿Las conclusiones responden la pregunta sin exceder el diseño?', '¿La discusión retoma los antecedentes construidos?'], ['manual','qual','quant','mixed']),
  lesson('referencias', 'Citas y referencias APA 7', 'Comunicar',
    'La cita identifica la fuente de una afirmación; la referencia permite localizarla. La paráfrasis conserva el sentido y también requiere atribución.',
    'Hacer rastreable el argumento y reconocer el trabajo previo.', 'Durante la escritura, no solo al final.',
    ['Identifica el tipo de documento y sus datos reales.', 'Comprueba autor, fecha, título y fuente.', 'Vincula cada cita con su referencia.', 'Verifica DOI o URL y ubicación de citas textuales.'],
    'Cooke et al. (2012) proponen SPIDER para estructurar búsquedas de evidencia cualitativa y mixta.', 'Un autor demuestra que el enfoque mixto siempre es mejor (sin fuente).',
    'La atribución debe sostener la afirmación específica; un listado bibliográfico no repara una afirmación sin respaldo.',
    'Encuentras una referencia incompleta. ¿Qué datos puedes reconstruir por suposición?',
    'Ninguno: consulta el documento o registro original. Si no puedes verificar un dato, conserva la tarea pendiente.',
    [['citations','Afirmaciones y sus citas','Muestra qué fuente sostiene cada afirmación.'],['references','Referencias verificadas','Una por línea; comprueba los datos en la fuente.'],['pending','Datos por comprobar','Registra dudas y cómo resolverlas.']],
    ['¿Toda cita tiene una referencia y viceversa?', '¿Las fuentes respaldan lo que les atribuyo?'], ['apa','spider']),
  lesson('defensa', 'Defensa y coherencia del proyecto', 'Comunicar',
    'Defender un proyecto es explicar sus decisiones y límites con razones. La revisión de coherencia comprueba que problema, pregunta, objetivos y método sostienen una misma investigación.',
    'Reconocer contradicciones y fundamentar decisiones ante preguntas.', 'En cada revisión del proyecto y antes de presentarlo.',
    ['Explica el problema en un minuto.', 'Conecta pregunta y objetivo general.', 'Justifica lente, fuentes y método.', 'Distingue decisiones consolidadas y pendientes.', 'Ensaya una objeción y revisa tu respuesta.'],
    'El diseño específico está pendiente; tenemos una razón para integrar evidencia, pero aún debemos precisar cómo.', 'Todo está validado porque completamos las casillas.',
    'Una actividad completada registra trabajo realizado. No acredita por sí sola la calidad científica.',
    'Responde: «¿Qué cambiaría en tu estudio si no aparece la relación esperada?».',
    'Un resultado nulo o discrepante sigue siendo informativo. La interpretación se ajusta a la evidencia y no se fuerza para confirmar expectativas.',
    [['account','Mi explicación del proyecto','Problema, pregunta, objetivo y propuesta metodológica.'],['objection','Objeción y respuesta','Razones, fuentes y límites.'],['next','Qué debemos revisar','Decisiones pendientes y apartados afectados.']],
    ['¿Puedo explicar la continuidad problema–pregunta–objetivos–método?', '¿Reconozco qué sigue abierto?'], ['manual','feedback']),
  ...collaborationLessons(lesson)
];

export const SEARCH_SOURCES = [
  ['ERIC', 'https://eric.ed.gov/', 'Educación: artículos e informes. Revisa descriptores y tipo de publicación; identifica cuáles tienen revisión por pares.'],
  ['SciELO', 'https://search.scielo.org/', 'Revistas de distintas disciplinas y producción regional. Prueba términos en español, portugués e inglés según el tema.'],
  ['PubMed', 'https://pubmed.ncbi.nlm.nih.gov/', 'Salud y áreas afines. Combina términos libres y MeSH cuando corresponda; revisa cómo se interpretó la consulta.'],
  ['APA PsycINFO', 'https://www.apa.org/pubs/databases/psycinfo', 'Psicología y disciplinas relacionadas. Consulta el acceso institucional y el tesauro de la plataforma contratada.'],
  ['Google Académico', 'https://scholar.google.com/', 'Descubrimiento amplio y rastreo de citas. Verifica versión y tipo de documento; no asumas revisión por pares.'],
  ['Scopus', 'https://www.scopus.com/', 'Índice multidisciplinar y citas. El acceso puede depender de tu institución.'],
  ['Web of Science', 'https://www.webofscience.com/', 'Colecciones e índices de citas. Registra qué colección y filtros utilizaste.'],
  ['LA Referencia', 'https://www.lareferencia.info/', 'Repositorios latinoamericanos: tesis y otros trabajos. Verifica institución, versión y tipo de documento.']
];

export function buildBoolean(blocks) {
  return blocks.map(block => [...new Set(String(block).split(/[,;\n]/).map(term => term.trim().replace(/^["“”]+|["“”]+$/g, '')).filter(Boolean))])
    .filter(block => block.length).map(block => '(' + block.map(term => /\s/.test(term) ? '"' + term.replace(/"/g, '') + '"' : term).join(' OR ') + ')').join(' AND ');
}

export function computeFlow(searches = [], flow = {}) {
  const count = value => value !== '' && value != null && Number.isSafeInteger(Number(value)) && Number(value) >= 0;
  const fields = ['duplicates','other','screenedOut','notRetrieved','fullExcluded'];
  if (!searches.length || searches.some(row => !count(row.count)) || fields.some(key => !count(flow[key]))) return { error: 'Completa los conteos reales con enteros no negativos. Un campo vacío no equivale a cero.' };
  const total = searches.reduce((sum, row) => sum + Number(row.count), 0);
  if (!Number.isSafeInteger(total)) return { error: 'El total excede el rango de conteo admitido.' };
  const screened = total - Number(flow.duplicates) - Number(flow.other);
  const sought = screened - Number(flow.screenedOut);
  const assessed = sought - Number(flow.notRetrieved);
  const included = assessed - Number(flow.fullExcluded);
  if ([screened,sought,assessed,included].some(n => n < 0)) return { error: 'Hay más exclusiones que registros disponibles en una etapa. Revisa la bitácora.' };
  if (Number(flow.fullExcluded) > 0 && !String(flow.reasons || '').trim()) return { error: 'Documenta las razones de exclusión de textos completos y sus cantidades.' };
  return { total, screened, sought, assessed, included };
}

export function reviewSnapshot(record = {}) {
  return JSON.stringify({ fields: record.fields || {}, practice: record.practice || '', reflection: record.reflection || '', source: record.source || '', tools: record.tools || {}, ...(record.learning?.reason || record.learning?.alternative ? { practiceRationale: { reason: record.learning.reason || '', alternative: record.learning.alternative || '' } } : {}), ...(record.learning?.teachingReason || record.learning?.teachingRevision ? { guidedDecision: { choice:record.learning.teachingChoice || '', reason:record.learning.teachingReason || '', revision:record.learning.teachingRevision || '' } } : {}), ...(record.learning?.transfer || record.learning?.transferReason ? { transfer: { answer:record.learning.transfer || '', reason:record.learning.transferReason || '' } } : {}) });
}
export function isLessonReviewed(record = {}) {
  return !!record.review && record.review.snapshot === reviewSnapshot(record);
}
export function draftText(lesson, record = {}) {
  return lesson.fields.map(field => field.label + ':\n' + (record.fields?.[field.key] || '(pendiente)')).join('\n\n');
}
export function structuralFeedback(lesson, record = {}) {
  const notes = [];
  for (const field of lesson.fields) if (!String(record.fields?.[field.key] || '').trim()) notes.push('Falta desarrollar «' + field.label + '». ' + field.help);
  if (!String(record.source || '').trim()) notes.push('Identifica la fuente y el pasaje que sustentan tu desarrollo. No basta una bibliografía general.');
  const text = draftText(lesson, record);
  if (/nadie ha|no existe ninguna|demostrar que|siempre mejora/i.test(text)) notes.push('Revisa la afirmación absoluta: delimita el corpus o evita anticipar un resultado.');
  if (lesson.id === 'objetivos' && /(?:^|\n)\s*(?:\d+[.)]\s*)?(?:aplicar|descargar|realizar entrevistas|hacer encuestas)\b/i.test(record.fields?.specifics || '')) notes.push('Puede haber una tarea metodológica entre los objetivos. Expresa qué conocimiento produciría.');
  if (!notes.length) notes.push('Los campos de desarrollo y respaldo tienen contenido. Contrasta ahora el argumento con las preguntas de coherencia; esta comprobación no certifica la validez de las fuentes ni del razonamiento.');
  return notes;
}
