// Verified references and explicit teaching adaptations; no efficacy claim for this platform.
export const PEDAGOGY_EVIDENCE = [
  {
    "id": "retrieval",
    "label": "Dunlosky et al. (2013)",
    "title": "Recuperación y práctica distribuida",
    "kind": "Revisión de técnicas de aprendizaje.",
    "application": "Recuperar una explicación sin mirar y retomarla en otra sesión.",
    "limit": "La utilidad depende de tarea y condiciones; un calendario no demuestra retención.",
    "citation": "Dunlosky, J., Rawson, K. A., Marsh, E. J., Nathan, M. J., & Willingham, D. T. (2013). Improving students’ learning with effective learning techniques: Promising directions from cognitive and educational psychology. Psychological Science in the Public Interest, 14(1), 4–58.",
    "url": "https://doi.org/10.1177/1529100612453266",
    "action": "Practicar y repasar",
    "module": "tema",
    "step": 2
  },
  {
    "id": "explanation",
    "label": "Bisra et al. (2018)",
    "title": "Autoexplicación",
    "kind": "Metaanálisis de intervenciones de autoexplicación.",
    "application": "Explicar las razones de una decisión y una alternativa considerada.",
    "limit": "Completar un campo de razones no asegura su calidad; hay que contrastarlo.",
    "citation": "Bisra, K., Liu, Q., Nesbit, J. C., Salimi, F., & Winne, P. H. (2018). Inducing Self-Explanation: a Meta-Analysis. Educational Psychology Review, 30(3), 703–725.",
    "url": "https://doi.org/10.1007/s10648-018-9434-x",
    "action": "Justificar mis decisiones",
    "module": "objetivos",
    "step": 2
  },
  {
    "id": "selfregulation",
    "label": "Panadero (2017)",
    "title": "Autorregulación",
    "kind": "Revisión conceptual de seis modelos.",
    "application": "Formular una meta, reconocer dificultades y decidir el siguiente ajuste.",
    "limit": "Es un marco conceptual; no es una evaluación de este simulador.",
    "citation": "Panadero, E. (2017). A Review of Self-regulated Learning: Six Models and Four Directions for Research. Frontiers in Psychology, 8, 422.",
    "url": "https://doi.org/10.3389/fpsyg.2017.00422",
    "action": "Planificar mi aprendizaje",
    "module": "tema",
    "step": 0
  },
  {
    "id": "cognitive",
    "label": "Sweller, van Merriënboer y Paas (2019)",
    "title": "Ayudas graduales",
    "kind": "Desarrollo teórico de carga cognitiva y diseño instruccional.",
    "application": "Integrar ejemplos, pistas y pasos cerca de la tarea; permitir resolver con menos apoyo.",
    "limit": "La ayuda debe ajustarse al conocimiento previo y la complejidad.",
    "citation": "Sweller, J., van Merriënboer, J. J. G., & Paas, F. (2019). Cognitive Architecture and Instructional Design: 20 Years Later. Educational Psychology Review, 31(2), 261–292.",
    "url": "https://doi.org/10.1007/s10648-019-09465-5",
    "action": "Elegir mis apoyos",
    "module": "booleanas",
    "step": 2
  },
  {
    "id": "feedbackReview",
    "label": "Wisniewski, Zierer y Hattie (2020)",
    "title": "Retroalimentación informativa",
    "kind": "Metaanálisis de retroalimentación educativa.",
    "application": "Relacionar observación, criterio y próxima acción; conservar la revisión del intento.",
    "limit": "El efecto varía según el contenido y el contexto; cualquier comentario no equivale a ayuda eficaz.",
    "citation": "Wisniewski, B., Zierer, K., & Hattie, J. (2020). The power of feedback revisited: A meta-analysis of educational feedback research. Frontiers in Psychology, 10, 3087.",
    "url": "https://doi.org/10.3389/fpsyg.2019.03087",
    "action": "Revisar un desarrollo",
    "module": "pregunta",
    "step": 4
  },
  {
    "id": "active",
    "label": "Allen y Baughman (2016)",
    "title": "Aprender metodología haciendo",
    "kind": "Comparación experimental de talleres de métodos de investigación.",
    "application": "Resolver una tarea, analizar evidencia de entrenamiento y justificar su alcance.",
    "limit": "Muestra pequeña; conocimiento, confianza y satisfacción son resultados diferentes.",
    "citation": "Allen, P. J., & Baughman, F. D. (2016). Active Learning in Research Methods Classes Is Associated with Higher Knowledge and Confidence, Though not Evaluations or Satisfaction. Frontiers in Psychology, 7, 279.",
    "url": "https://doi.org/10.3389/fpsyg.2016.00279",
    "action": "Ensayar una decisión metodológica",
    "module": "diseno",
    "step": 5
  },
  {
    "id": "simulation",
    "label": "Chernikova et al. (2020)",
    "title": "Aprendizaje por simulación",
    "kind": "Metaanálisis en educación superior.",
    "application": "Practicar decisiones con tareas contextualizadas y apoyos; transferir luego al proyecto.",
    "limit": "Resultados heterogéneos y ámbitos distintos; no acreditan la eficacia de esta plataforma.",
    "citation": "Chernikova, O., Heitzmann, N., Stadler, M., Holzberger, D., Seidel, T., & Fischer, F. (2020). Simulation-Based Learning in Higher Education: A Meta-Analysis. Review of Educational Research, 90(4), 499–541.",
    "url": "https://doi.org/10.3102/0034654320933544",
    "action": "Practicar con un caso",
    "module": "pares",
    "step": 1
  },
  {
    "id": "simulationDesign",
    "label": "Cook et al. (2013)",
    "title": "Diseño de las simulaciones",
    "kind": "Revisión sistemática y metaanálisis en educación sanitaria.",
    "application": "Variar la dificultad, volver a practicar y usar retroalimentación específica.",
    "limit": "Procede de formación sanitaria; el traslado a investigación es una adaptación.",
    "citation": "Cook, D. A., Hamstra, S. J., Brydges, R., Zendejas, B., Szostek, J. H., Wang, A. T., Erwin, P. J., & Hatala, R. (2013). Comparative effectiveness of instructional design features in simulation-based education: Systematic review and meta-analysis. Medical Teacher, 35(1), e867–e898.",
    "url": "https://doi.org/10.3109/0142159x.2012.714886",
    "action": "Volver a intentar",
    "module": "embudo",
    "step": 2
  },
  {
    "id": "adaptivity",
    "label": "Chernikova et al. (2025)",
    "title": "Orientación y elección",
    "kind": "Metaanálisis sobre adaptividad y adaptabilidad.",
    "application": "Ofrecer recomendaciones explicadas y permitir elegir tarea, apoyo y progresión.",
    "limit": "Las sugerencias del aula son reglas visibles de orientación, no una medición de dominio.",
    "citation": "Chernikova, O., Sommerhoff, D., Stadler, M., Holzberger, D., Nickl, M., Seidel, T., Kasneci, E., Küchemann, S., Kuhn, J., Fischer, F., & Heitzmann, N. (2025). Personalization through adaptivity or adaptability? A meta-analysis on simulation-based learning in higher education. Educational Research Review, 46, 100662.",
    "url": "https://doi.org/10.1016/j.edurev.2024.100662",
    "action": "Comparar rutas",
    "module": "diseno",
    "step": 0
  },
  {
    "id": "reger",
    "label": "Reger et al. (2020)",
    "title": "Desempeño y seguimiento",
    "kind": "Ensayo aleatorizado de entrenamiento en entrevista motivacional.",
    "application": "Conservar productos observables y revisarlos también en tareas posteriores.",
    "limit": "El contexto es clínico; no demuestra transferencia ni eficacia para una tesis.",
    "citation": "Reger, G. M., Norr, A. M., Rizzo, A. S., Sylvers, P., Peltan, J., Fischer, D., Trimmer, M., Porter, S., Gant, P., & Baer, J. S. (2020). Virtual Standardized Patients vs Academic Training for Learning Motivational Interviewing Skills in the US Department of Veterans Affairs and the US Military: A Randomized Trial. JAMA Network Open, 3(10), e2017348.",
    "url": "https://doi.org/10.1001/jamanetworkopen.2020.17348",
    "action": "Transferir a otra tarea",
    "module": "defensa",
    "step": 5
  },
  {
    "id": "louie",
    "label": "Louie et al. (2026)",
    "title": "Práctica con retroalimentación",
    "kind": "Estudio aleatorizado de entrenamiento de consejeros noveles.",
    "application": "Contrastar un intento y justificar su revisión antes de volver a aplicar.",
    "limit": "Evaluación conductual automatizada e inmediata; requiere contraste humano y no acredita transferencia clínica real.",
    "citation": "Louie, R., Shah, R. S., Orney, I. H., Pacheco, J. P., Brunskill, E., & Yang, D. (2026). Can LLM-Simulated Practice and Feedback Upskill Human Counselors? A Randomized Study with 90+ Novice Counselors. Proceedings of the 2026 CHI Conference on Human Factors in Computing Systems, 1–31.",
    "url": "https://doi.org/10.1145/3772318.3791821",
    "action": "Contrastar con pares",
    "module": "pares",
    "step": 2
  },
  {
    "id": "cecil",
    "label": "Cecil et al. (2026)",
    "title": "Confianza y aprendizaje",
    "kind": "Estudio de pacientes virtuales frente a videos.",
    "application": "Separar dificultad o confianza declarada de la calidad del producto investigativo.",
    "limit": "Los cambios en competencia percibida no equivalen a mejoras de conocimiento; la simulación no superó al video en ese estudio.",
    "citation": "Cecil, J., Kokje, E., Kleine, A.-K., Schaffernak, I., Vogel, L., Angerer, S., Lermer, E., & Gaube, S. (2026). The effect of AI-enabled virtual patient simulation on training outcomes and insecurities in psychotherapy education. BMC Medical Education, 26(1), 1156.",
    "url": "https://doi.org/10.1186/s12909-026-09917-x",
    "action": "Examinar mi evidencia",
    "module": "antecedentes",
    "step": 0
  },
  {
    "id": "fourcid",
    "label": "van Merriënboer (2019)",
    "title": "Modelo 4C/ID",
    "kind": "Guía de diseño para aprendizaje complejo.",
    "application": "Conservar una tarea completa —el proyecto— y situar dentro de ella información de apoyo, instrucciones para procedimientos y práctica de componentes.",
    "limit": "Esta aula adapta esos principios; no declara una implementación validada del modelo.",
    "citation": "van Merriënboer, J. J. G. (2019). The four-component instructional design model: An overview of its main design principles [Guía]. Maastricht University.",
    "url": "https://www.4cid.org/wp-content/uploads/2021/04/vanmerrienboer-4cid-overview-of-main-design-principles-2021.pdf",
    "action": "Conectar el proyecto",
    "module": "defensa",
    "step": 5
  },
  {
    "id": "learningScientists",
    "label": "The Learning Scientists",
    "title": "Materiales en español",
    "kind": "Recursos divulgativos sobre estrategias de aprendizaje.",
    "application": "Consultar afiches y diapositivas para ampliar las explicaciones sobre recuperación y práctica espaciada.",
    "limit": "Son materiales de apoyo; no sustituyen la lectura de los estudios ni evalúan tu proyecto.",
    "citation": "The Learning Scientists. (s. f.). Translations.",
    "url": "https://www.learningscientists.org/translations",
    "action": "Repasar un concepto",
    "module": "booleanas",
    "step": 2
  },
  {
    "id": "inacsl",
    "label": "INACSL · estándares de simulación",
    "title": "Preparar, facilitar y reflexionar",
    "kind": "Estándares de buenas prácticas en simulación sanitaria; apartados revisados en 2025.",
    "application": "Explicitar objetivos y condiciones antes de practicar; facilitar la tarea y cerrar con reflexión sobre las decisiones.",
    "limit": "Su ámbito es sanitario. Esta adaptación didáctica a investigación no supone certificación ni cumplimiento integral.",
    "citation": "International Nursing Association for Clinical Simulation and Learning. (s. f.). Healthcare simulation standards of best practice.",
    "url": "https://www.inacsl.org/healthcare-simulation-standards-ql",
    "action": "Preparar una práctica",
    "module": "diseno",
    "step": 2
  }
];
